export type FinancialCalendarView =
  | "month"
  | "week"
  | "agenda";

export type FinancialCalendarEventType =
  | "bill"
  | "paycheck"
  | "transaction"
  | "income"
  | "savings-contribution"
  | "debt-payment"
  | "transfer"
  | "reminder"
  | "custom";

export type FinancialCalendarEventStatus =
  | "scheduled"
  | "due"
  | "past-due"
  | "pending"
  | "completed"
  | "skipped"
  | "canceled";

export type FinancialCalendarEventPriority =
  | "critical"
  | "high"
  | "normal"
  | "low";

export type FinancialCalendarRecurrenceFrequency =
  | "daily"
  | "weekly"
  | "biweekly"
  | "semimonthly"
  | "monthly"
  | "quarterly"
  | "yearly"
  | "custom";

export type FinancialCalendarRecurrenceEndType =
  | "never"
  | "date"
  | "occurrences";

export type FinancialCalendarWeekday =
  | 0
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6;

export type FinancialCalendarRecurrenceRule = {
  frequency:
    FinancialCalendarRecurrenceFrequency;

  interval: number;

  weekdays?:
    FinancialCalendarWeekday[];

  dayOfMonth?: number;

  firstDayOfMonth?: number;
  secondDayOfMonth?: number;

  monthOfYear?: number;

  endType:
    FinancialCalendarRecurrenceEndType;

  endDate?: string;
  occurrenceCount?: number;
};

export type FinancialCalendarReminderUnit =
  | "minute"
  | "hour"
  | "day"
  | "week";

export type FinancialCalendarReminder = {
  id: string;

  amount: number;
  unit:
    FinancialCalendarReminderUnit;

  isEnabled: boolean;
};

export type FinancialCalendarSourceType =
  | "bill"
  | "pay-cycle"
  | "transaction"
  | "goal"
  | "debt"
  | "account"
  | "manual";

export type FinancialCalendarEventSource = {
  type:
    FinancialCalendarSourceType;

  id: string;
};

export type FinancialCalendarEvent = {
  id: string;

  title: string;
  description?: string;
  notes?: string;

  type:
    FinancialCalendarEventType;

  status:
    FinancialCalendarEventStatus;

  priority:
    FinancialCalendarEventPriority;

  date: string;

  startTime?: string;
  endTime?: string;

  isAllDay: boolean;

  amount?: number;

  accountId?: string;
  categoryId?: string;

  source?:
    FinancialCalendarEventSource;

  recurrence?:
    FinancialCalendarRecurrenceRule;

  reminders:
    FinancialCalendarReminder[];

  isAutoGenerated: boolean;

  createdAt: string;
  updatedAt: string;
};

export type CreateFinancialCalendarEventData = {
  title: string;
  description?: string;
  notes?: string;

  type:
    FinancialCalendarEventType;

  status:
    FinancialCalendarEventStatus;

  priority:
    FinancialCalendarEventPriority;

  date: string;

  startTime?: string;
  endTime?: string;

  isAllDay: boolean;

  amount?: number;

  accountId?: string;
  categoryId?: string;

  recurrence?:
    FinancialCalendarRecurrenceRule;

  reminders:
    FinancialCalendarReminder[];
};

export type UpdateFinancialCalendarEventData = {
  id: string;

  title: string;
  description?: string;
  notes?: string;

  type:
    FinancialCalendarEventType;

  status:
    FinancialCalendarEventStatus;

  priority:
    FinancialCalendarEventPriority;

  date: string;

  startTime?: string;
  endTime?: string;

  isAllDay: boolean;

  amount?: number;

  accountId?: string;
  categoryId?: string;

  recurrence?:
    FinancialCalendarRecurrenceRule;

  reminders:
    FinancialCalendarReminder[];
};

export type FinancialCalendarEventOccurrence = {
  id: string;

  eventId: string;

  date: string;

  startTime?: string;
  endTime?: string;

  status:
    FinancialCalendarEventStatus;

  isRecurringOccurrence: boolean;

  originalDate?: string;

  event:
    FinancialCalendarEvent;
};

export type FinancialCalendarDateRange = {
  startDate: string;
  endDate: string;
};

export type FinancialCalendarFilters = {
  search: string;

  eventTypes:
    FinancialCalendarEventType[];

  statuses:
    FinancialCalendarEventStatus[];

  priorities:
    FinancialCalendarEventPriority[];

  accountIds: string[];

  includeCompleted: boolean;
  includeCanceled: boolean;
  includeAutoGenerated: boolean;
  includeManual: boolean;
};

export type FinancialCalendarDay = {
  date: string;

  isCurrentMonth: boolean;
  isToday: boolean;
  isSelected: boolean;
  isWeekend: boolean;

  occurrences:
    FinancialCalendarEventOccurrence[];

  totalScheduledAmount: number;
  totalIncomeAmount: number;
  totalExpenseAmount: number;

  dueCount: number;
  pastDueCount: number;
  completedCount: number;
};

export type FinancialCalendarWeek = {
  id: string;

  startDate: string;
  endDate: string;

  days:
    FinancialCalendarDay[];
};

export type FinancialCalendarMonth = {
  month: number;
  year: number;

  startDate: string;
  endDate: string;

  weeks:
    FinancialCalendarWeek[];
};

export type FinancialCalendarAgendaGroup = {
  date: string;
  label: string;

  occurrences:
    FinancialCalendarEventOccurrence[];

  totalIncomeAmount: number;
  totalExpenseAmount: number;
};

export type FinancialCalendarSummary = {
  totalEventCount: number;

  upcomingEventCount: number;
  dueTodayCount: number;
  pastDueCount: number;
  completedCount: number;

  upcomingBillCount: number;
  upcomingPaycheckCount: number;

  scheduledIncomeAmount: number;
  scheduledExpenseAmount: number;

  netScheduledCashFlow: number;

  nextEventDate?: string;
  nextPaycheckDate?: string;
  nextBillDueDate?: string;
};

export type FinancialCalendarConflictType =
  | "insufficient-funds"
  | "multiple-critical-bills"
  | "bill-before-paycheck"
  | "overlapping-autopay"
  | "past-due"
  | "missing-account"
  | "missing-income";

export type FinancialCalendarConflictSeverity =
  | "info"
  | "warning"
  | "critical";

export type FinancialCalendarConflict = {
  id: string;

  type:
    FinancialCalendarConflictType;

  severity:
    FinancialCalendarConflictSeverity;

  title: string;
  description: string;

  date: string;

  eventIds: string[];

  amount?: number;
  availableAmount?: number;
  shortageAmount?: number;

  actionLabel?: string;
  actionHref?: string;
};

export type FinancialCalendarPreferences = {
  defaultView:
    FinancialCalendarView;

  weekStartsOn:
    FinancialCalendarWeekday;

  showWeekends: boolean;

  showBills: boolean;
  showPaychecks: boolean;
  showTransactions: boolean;
  showSavingsContributions: boolean;
  showDebtPayments: boolean;
  showTransfers: boolean;
  showReminders: boolean;
  showCustomEvents: boolean;

  showCompletedEvents: boolean;
  showCanceledEvents: boolean;

  enableConflictDetection: boolean;

  defaultReminderAmount: number;
  defaultReminderUnit:
    FinancialCalendarReminderUnit;
};

export type FinancialCalendarState = {
  selectedDate: string;

  visibleRange:
    FinancialCalendarDateRange;

  view:
    FinancialCalendarView;

  filters:
    FinancialCalendarFilters;

  preferences:
    FinancialCalendarPreferences;
};

/**
 * ---------------------------------------------------------------------------
 * Production persistence contracts
 * ---------------------------------------------------------------------------
 *
 * Manual calendar events and persistent calendar preferences are stored in
 * Supabase. Generated bill/paycheck/transaction/etc. calendar events remain
 * derived from their canonical production records and are not duplicated.
 *
 * These result contracts are used by authenticated server actions and the
 * CalendarProvider. No localStorage/sessionStorage persistence is required.
 */

export type FinancialCalendarPersistentFilters = {
  search: string;

  eventTypes:
    FinancialCalendarEventType[];

  statuses:
    FinancialCalendarEventStatus[];

  priorities:
    FinancialCalendarEventPriority[];

  accountIds: string[];

  includeCompleted: boolean;
  includeCanceled: boolean;
  includeAutoGenerated: boolean;
  includeManual: boolean;
};

export type FinancialCalendarPreferenceData = {
  id: string;

  defaultView:
    FinancialCalendarView;

  weekStartsOn:
    FinancialCalendarWeekday;

  showWeekends: boolean;

  enableConflictDetection: boolean;

  selectedDate?: string;

  filters:
    FinancialCalendarPersistentFilters;

  createdAt: string;
  updatedAt: string;
};

export type UpdateFinancialCalendarPreferencesData = {
  defaultView?:
    FinancialCalendarView;

  weekStartsOn?:
    FinancialCalendarWeekday;

  showWeekends?:
    boolean;

  enableConflictDetection?:
    boolean;

  selectedDate?:
    string | null;

  filters?:
    FinancialCalendarPersistentFilters;
};

export type CalendarFieldErrors<T> =
  Partial<
    Record<
      keyof T,
      string
    >
  >;

export type GetFinancialCalendarEventsResult =
  | {
      success: true;

      events:
        FinancialCalendarEvent[];
    }
  | {
      success: false;

      error: string;
    };

export type CreateFinancialCalendarEventResult =
  | {
      success: true;

      event:
        FinancialCalendarEvent;
    }
  | {
      success: false;

      error: string;

      fieldErrors?:
        CalendarFieldErrors<
          CreateFinancialCalendarEventData
        >;
    };

export type UpdateFinancialCalendarEventResult =
  | {
      success: true;

      event:
        FinancialCalendarEvent;
    }
  | {
      success: false;

      error: string;

      fieldErrors?:
        CalendarFieldErrors<
          UpdateFinancialCalendarEventData
        >;
    };

export type ArchiveFinancialCalendarEventResult =
  | {
      success: true;

      event:
        FinancialCalendarEvent;

      archived:
        boolean;
    }
  | {
      success: false;

      error: string;
    };

export type GetFinancialCalendarPreferencesResult =
  | {
      success: true;

      preferences:
        FinancialCalendarPreferenceData;
    }
  | {
      success: false;

      error: string;
    };

export type UpdateFinancialCalendarPreferencesResult =
  | {
      success: true;

      preferences:
        FinancialCalendarPreferenceData;
    }
  | {
      success: false;

      error: string;

      fieldErrors?:
        CalendarFieldErrors<
          UpdateFinancialCalendarPreferencesData
        >;
    };

