/**
 * CASE Budget Supabase database types.
 *
 * File:
 * apps/case-budget/types/database.ts
 *
 * This file is the central TypeScript representation layer for
 * the CASE Budget Supabase/PostgreSQL database.
 *
 * IMPORTANT:
 *
 * CASE Budget already has an existing Supabase database.
 * This file does NOT create, migrate, alter, or otherwise modify
 * that database.
 *
 * It exists only to provide reusable TypeScript types for:
 *
 * - Supabase table rows
 * - insert payloads
 * - update payloads
 * - database functions / RPCs
 * - JSON values
 * - generated database types
 *
 * The current CASE Budget application already communicates with
 * Supabase successfully without passing a Database generic to every
 * Supabase client.
 *
 * This file therefore remains intentionally non-destructive and
 * incrementally typed.
 *
 * Strongly typed definitions are added only for schema objects that
 * have been confirmed against the existing Supabase database.
 */

/**
 * JSON-compatible values supported by PostgreSQL json/jsonb
 * columns and Supabase generated database types.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | {
      [key: string]:
        Json | undefined;
    }
  | Json[];

/**
 * Foreign-key relationship metadata used by generated Supabase
 * database types.
 */
export type SupabaseRelationship = {
  foreignKeyName:
    string;

  columns:
    string[];

  isOneToOne:
    boolean;

  referencedRelation:
    string;

  referencedColumns:
    string[];
};

/**
 * Common shape used by Supabase-generated table definitions.
 *
 * Row:
 *   The complete record returned by SELECT operations.
 *
 * Insert:
 *   Values accepted when creating a new record.
 *
 * Update:
 *   Values accepted when modifying an existing record.
 *
 * Relationships:
 *   Foreign-key relationship metadata generated by Supabase.
 */
export type SupabaseTableDefinition<
  Row extends Record<
    string,
    unknown
  > = Record<
    string,
    unknown
  >,
  Insert extends Record<
    string,
    unknown
  > = Partial<Row>,
  Update extends Record<
    string,
    unknown
  > = Partial<Insert>,
> = {
  Row:
    Row;

  Insert:
    Insert;

  Update:
    Update;

  Relationships:
    SupabaseRelationship[];
};

/**
 * Generic RPC definition.
 */
export type SupabaseFunctionDefinition<
  Args extends Record<
    string,
    unknown
  > = Record<
    string,
    unknown
  >,
  Returns = Json,
> = {
  Args:
    Args;

  Returns:
    Returns;
};

/**
 * Generic database table fallback.
 *
 * This allows CASE Budget to continue using tables that have not yet
 * been added to the strongly typed schema section below.
 *
 * Once the complete generated Supabase schema is imported, this
 * fallback can be removed.
 */
export type GenericDatabaseRow =
  Record<
    string,
    unknown
  >;

export type GenericDatabaseInsert =
  Record<
    string,
    unknown
  >;

export type GenericDatabaseUpdate =
  Record<
    string,
    unknown
  >;

export type GenericDatabaseTable =
  SupabaseTableDefinition<
    GenericDatabaseRow,
    GenericDatabaseInsert,
    GenericDatabaseUpdate
  >;

/**
 * Confirmed PostgreSQL enum:
 *
 * public.workspace_type
 */
export type WorkspaceTypeDatabaseEnum =
  | "personal"
  | "household"
  | "business"
  | "organization";

/**
 * Confirmed PostgreSQL enum:
 *
 * public.workspace_role
 */
export type WorkspaceRoleDatabaseEnum =
  | "owner"
  | "admin"
  | "member"
  | "viewer";

/**
 * Confirmed PostgreSQL enum:
 *
 * public.workspace_membership_status
 */
export type WorkspaceMembershipStatusDatabaseEnum =
  | "invited"
  | "active"
  | "suspended"
  | "removed";

/**
 * public.workspaces
 *
 * Confirmed columns:
 *
 * id
 * name
 * slug
 * workspace_type
 * owner_user_id
 * description
 * logo_url
 * is_active
 * created_at
 * updated_at
 */
export type WorkspaceDatabaseRow = {
  id:
    string;

  name:
    string;

  slug:
    string;

  workspace_type:
    WorkspaceTypeDatabaseEnum;

  owner_user_id:
    string;

  description:
    string | null;

  logo_url:
    string | null;

  is_active:
    boolean;

  created_at:
    string;

  updated_at:
    string;
};

export type WorkspaceDatabaseInsert = {
  id?:
    string;

  name:
    string;

  slug:
    string;

  workspace_type?:
    WorkspaceTypeDatabaseEnum;

  owner_user_id:
    string;

  description?:
    string | null;

  logo_url?:
    string | null;

  is_active?:
    boolean;

  created_at?:
    string;

  updated_at?:
    string;
};

export type WorkspaceDatabaseUpdate = {
  id?:
    string;

  name?:
    string;

  slug?:
    string;

  workspace_type?:
    WorkspaceTypeDatabaseEnum;

  owner_user_id?:
    string;

  description?:
    string | null;

  logo_url?:
    string | null;

  is_active?:
    boolean;

  created_at?:
    string;

  updated_at?:
    string;
};

export type WorkspaceDatabaseTable =
  SupabaseTableDefinition<
    WorkspaceDatabaseRow,
    WorkspaceDatabaseInsert,
    WorkspaceDatabaseUpdate
  >;

/**
 * public.workspace_members
 *
 * Confirmed columns:
 *
 * id
 * workspace_id
 * user_id
 * role
 * status
 * invited_by
 * invited_at
 * invitation_expires_at
 * joined_at
 * suspended_at
 * suspended_by
 * suspension_reason
 * removed_at
 * removed_by
 * removal_reason
 * member_label
 * created_at
 * updated_at
 */
export type WorkspaceMemberDatabaseRow = {
  id:
    string;

  workspace_id:
    string;

  user_id:
    string;

  role:
    WorkspaceRoleDatabaseEnum;

  status:
    WorkspaceMembershipStatusDatabaseEnum;

  invited_by:
    string | null;

  invited_at:
    string | null;

  invitation_expires_at:
    string | null;

  joined_at:
    string | null;

  suspended_at:
    string | null;

  suspended_by:
    string | null;

  suspension_reason:
    string | null;

  removed_at:
    string | null;

  removed_by:
    string | null;

  removal_reason:
    string | null;

  member_label:
    string | null;

  created_at:
    string;

  updated_at:
    string;
};

export type WorkspaceMemberDatabaseInsert = {
  id?:
    string;

  workspace_id:
    string;

  user_id:
    string;

  role?:
    WorkspaceRoleDatabaseEnum;

  status?:
    WorkspaceMembershipStatusDatabaseEnum;

  invited_by?:
    string | null;

  invited_at?:
    string | null;

  invitation_expires_at?:
    string | null;

  joined_at?:
    string | null;

  suspended_at?:
    string | null;

  suspended_by?:
    string | null;

  suspension_reason?:
    string | null;

  removed_at?:
    string | null;

  removed_by?:
    string | null;

  removal_reason?:
    string | null;

  member_label?:
    string | null;

  created_at?:
    string;

  updated_at?:
    string;
};

export type WorkspaceMemberDatabaseUpdate = {
  id?:
    string;

  workspace_id?:
    string;

  user_id?:
    string;

  role?:
    WorkspaceRoleDatabaseEnum;

  status?:
    WorkspaceMembershipStatusDatabaseEnum;

  invited_by?:
    string | null;

  invited_at?:
    string | null;

  invitation_expires_at?:
    string | null;

  joined_at?:
    string | null;

  suspended_at?:
    string | null;

  suspended_by?:
    string | null;

  suspension_reason?:
    string | null;

  removed_at?:
    string | null;

  removed_by?:
    string | null;

  removal_reason?:
    string | null;

  member_label?:
    string | null;

  created_at?:
    string;

  updated_at?:
    string;
};

export type WorkspaceMemberDatabaseTable =
  SupabaseTableDefinition<
    WorkspaceMemberDatabaseRow,
    WorkspaceMemberDatabaseInsert,
    WorkspaceMemberDatabaseUpdate
  >;

/**
 * Known provisioning RPC result currently used by CASE Budget.
 *
 * This mirrors the result consumed by the authentication service.
 */
export type ProvisionCaseBudgetUserResult = {
  user_id:
    string;

  profile_id:
    string;

  workspace_id:
    string;

  membership_id:
    string;

  platform_role:
    string;

  profile_created:
    boolean;

  platform_role_created:
    boolean;

  workspace_created:
    boolean;

  membership_created:
    boolean;

  provisioned_at:
    string;
};

/**
 * Current broad application-level database definition.
 *
 * This intentionally remains permissive for tables that have not yet
 * been confirmed and added to this file.
 *
 * The strongly typed workspace definitions above are also exposed
 * through this type.
 *
 * The broad fallback prevents unrelated CASE Budget features from
 * breaking while the complete generated Supabase schema is still
 * being incorporated.
 */
export type Database = {
  public: {
    Tables: {
      workspaces:
        WorkspaceDatabaseTable;

      workspace_members:
        WorkspaceMemberDatabaseTable;

      [tableName: string]:
        GenericDatabaseTable;
    };

    Views:
      Record<
        string,
        {
          Row:
            GenericDatabaseRow;

          Relationships:
            SupabaseRelationship[];
        }
      >;

    Functions: {
      provision_case_budget_user: {
        Args: {
          target_user_id:
            string;
        };

        Returns:
          ProvisionCaseBudgetUserResult;
      };

      sync_case_budget_profile_from_auth: {
        Args: {
          target_user_id:
            string;
        };

        Returns:
          Json;
      };

      [functionName: string]:
        SupabaseFunctionDefinition;
    };

    Enums: {
      workspace_type:
        WorkspaceTypeDatabaseEnum;

      workspace_role:
        WorkspaceRoleDatabaseEnum;

      workspace_membership_status:
        WorkspaceMembershipStatusDatabaseEnum;

      [enumName: string]:
        string;
    };

    CompositeTypes:
      Record<
        string,
        unknown
      >;
  };
};

/**
 * Workspace-only database schema.
 *
 * This exists because Supabase's generic type resolver works best
 * when the table names are concrete literal keys rather than a broad
 * string index signature.
 *
 * Use this schema for clients or operations that specifically work
 * with:
 *
 * - public.workspaces
 * - public.workspace_members
 *
 * This provides strict Insert / Update / Row typing for the Create
 * Workspace flow without forcing the rest of CASE Budget onto an
 * incomplete generated schema.
 */
export type WorkspaceDatabase = {
  public: {
    Tables: {
      workspaces:
        WorkspaceDatabaseTable;

      workspace_members:
        WorkspaceMemberDatabaseTable;
    };

    Views: Record<
      never,
      never
    >;

    Functions: Record<
      never,
      never
    >;

    Enums: {
      workspace_type:
        WorkspaceTypeDatabaseEnum;

      workspace_role:
        WorkspaceRoleDatabaseEnum;

      workspace_membership_status:
        WorkspaceMembershipStatusDatabaseEnum;
    };

    CompositeTypes: Record<
      never,
      never
    >;
  };
};

/**
 * Utility aliases matching the structure of Supabase-generated
 * database types.
 */
export type DatabaseSchema =
  Database[
    "public"
  ];

export type DatabaseTables =
  DatabaseSchema[
    "Tables"
  ];

export type DatabaseViews =
  DatabaseSchema[
    "Views"
  ];

export type DatabaseFunctions =
  DatabaseSchema[
    "Functions"
  ];

export type DatabaseEnums =
  DatabaseSchema[
    "Enums"
  ];

/**
 * Resolves the Row type for a database table.
 */
export type TableRow<
  TableName extends keyof DatabaseTables,
> =
  DatabaseTables[
    TableName
  ] extends {
    Row:
      infer Row;
  }
    ? Row
    : never;

/**
 * Resolves the Insert type for a database table.
 */
export type TableInsert<
  TableName extends keyof DatabaseTables,
> =
  DatabaseTables[
    TableName
  ] extends {
    Insert:
      infer Insert;
  }
    ? Insert
    : never;

/**
 * Resolves the Update type for a database table.
 */
export type TableUpdate<
  TableName extends keyof DatabaseTables,
> =
  DatabaseTables[
    TableName
  ] extends {
    Update:
      infer Update;
  }
    ? Update
    : never;

/**
 * Resolves the Row type for a database view.
 */
export type ViewRow<
  ViewName extends keyof DatabaseViews,
> =
  DatabaseViews[
    ViewName
  ] extends {
    Row:
      infer Row;
  }
    ? Row
    : never;

/**
 * Resolves the argument type for a database RPC/function.
 */
export type FunctionArgs<
  FunctionName extends keyof DatabaseFunctions,
> =
  DatabaseFunctions[
    FunctionName
  ] extends {
    Args:
      infer Args;
  }
    ? Args
    : never;

/**
 * Resolves the return type for a database RPC/function.
 */
export type FunctionReturns<
  FunctionName extends keyof DatabaseFunctions,
> =
  DatabaseFunctions[
    FunctionName
  ] extends {
    Returns:
      infer Returns;
  }
    ? Returns
    : never;

/**
 * Utility for extracting nullable database fields.
 */
export type Nullable<
  Value,
> =
  Value | null;

/**
 * Utility for UUID-backed identifiers.
 *
 * UUIDs remain strings at runtime; this alias simply makes their
 * semantic purpose clearer in application and database code.
 */
export type DatabaseId =
  string;

/**
 * PostgreSQL timestamptz/date values are returned by Supabase as
 * strings.
 */
export type DatabaseTimestamp =
  string;

export type DatabaseDate =
  string;
