"use server";

import {
  CaseBudgetServerAuthError,
  requireCaseBudgetServerAuth,
} from "@/lib/auth/server-auth";


import {
  resolveAuthenticatedFeatureAccess,
} from "@/lib/subscriptions/subscription-access";

import {
  createWorkspaceAdminClient,
} from "@/lib/supabase/admin";

import type {
  Json,
  WorkspaceMembershipStatusDatabaseEnum,
} from "@/types/database";

import type {
  FinancialCalendarEventPriority,
  FinancialCalendarEventStatus,
  FinancialCalendarEventType,
  FinancialCalendarPersistentFilters,
  FinancialCalendarPreferenceData,
  FinancialCalendarView,
  FinancialCalendarWeekday,
  GetFinancialCalendarPreferencesResult,
} from "@/types/calendar";

type WorkspaceRow = {
  id:
    string;

  is_active:
    boolean;
};

type MembershipRow = {
  id:
    string;

  workspace_id:
    string;

  user_id:
    string;

  status:
    WorkspaceMembershipStatusDatabaseEnum;
};

type CalendarPreferenceRow = {
  id:
    string;

  workspace_id:
    string;

  user_id:
    string;

  default_view:
    string;

  week_starts_on:
    number;

  show_weekends:
    boolean;

  enable_conflict_detection:
    boolean;

  selected_date:
    string | null;

  filters:
    Json;

  created_at:
    string;

  updated_at:
    string;
};

const DEFAULT_FILTERS:
  FinancialCalendarPersistentFilters = {
    search:
      "",

    eventTypes:
      [],

    statuses:
      [],

    priorities:
      [],

    accountIds:
      [],

    includeCompleted:
      true,

    includeCanceled:
      false,

    includeAutoGenerated:
      true,

    includeManual:
      true,
  };

/**
 * Loads persistent calendar preferences for the authenticated user in the
 * authenticated active CASE Budget workspace.
 *
 * If no preference row exists yet, this action returns canonical defaults.
 * It intentionally does not insert a row on read. The update/upsert action is
 * responsible for persistence.
 *
 * No workspace ID or user ID is accepted from the client.
 * No localStorage or sessionStorage is used.
 */
export async function getCalendarPreferences():
  Promise<GetFinancialCalendarPreferencesResult> {
  try {
    const {
      userId,
      workspaceId,
    } =
      await requireCaseBudgetServerAuth();

    const featureAccess =
      await resolveAuthenticatedFeatureAccess({
        feature:
          "calendar",

        workspaceId,
      });

    if (
      !featureAccess.access.allowed
    ) {
      return failure(
        getCalendarFeatureAccessMessage({
          reason:
            featureAccess.access.reason,

          requiredPlan:
            featureAccess.access.requiredPlan,
        }),
      );
    }

    const workspaceResult =
      await loadWorkspace({
        workspaceId,
      });

    if (
      !workspaceResult.success
    ) {
      return failure(
        workspaceResult.message,
      );
    }

    const membershipResult =
      await loadMembership({
        workspaceId,
        userId,
      });

    if (
      !membershipResult.success
    ) {
      return failure(
        membershipResult.message,
      );
    }

    const admin =
      createWorkspaceAdminClient();

    const {
      data,
      error,
    } =
      await admin
        .from(
          "case_budget_calendar_preferences",
        )
        .select(
          "id,workspace_id,user_id,default_view,week_starts_on,show_weekends,enable_conflict_detection,selected_date,filters,created_at,updated_at",
        )
        .eq(
          "workspace_id",
          workspaceId,
        )
        .eq(
          "user_id",
          userId,
        )
        .maybeSingle();

    if (
      error
    ) {
      console.error(
        "[CASE Budget Calendar] Failed to load calendar preferences.",
        {
          workspaceId,
          userId,
          error,
        },
      );

      return failure(
        "CASE Budget could not load your calendar preferences.",
      );
    }

    if (
      !data
    ) {
      return {
        success:
          true,

        preferences:
          createDefaultPreferences(),
      };
    }

    const row =
      data as unknown as
        CalendarPreferenceRow;

    const preferences =
      mapPreferenceRow({
        row,
        workspaceId,
        userId,
      });

    if (
      !preferences
    ) {
      console.error(
        "[CASE Budget Calendar] Calendar preference row failed validation.",
        {
          workspaceId,
          userId,
          preferenceId:
            row.id,
        },
      );

      return failure(
        "CASE Budget found invalid calendar preference data.",
      );
    }

    return {
      success:
        true,

      preferences,
    };
  } catch (
    error
  ) {
    if (
      error instanceof
      CaseBudgetServerAuthError
    ) {
      return failure(
        error.message,
      );
    }

    console.error(
      "[CASE Budget Calendar] Unexpected get-calendar-preferences error.",
      error,
    );

    return failure(
      "CASE Budget could not load your calendar preferences. Please try again.",
    );
  }
}

async function loadWorkspace({
  workspaceId,
}: {
  workspaceId:
    string;
}):
  Promise<
    | {
        success:
          true;
      }
    | {
        success:
          false;

        message:
          string;
      }
  > {
  const admin =
    createWorkspaceAdminClient();

  const {
    data,
    error,
  } =
    await admin
      .from(
        "workspaces",
      )
      .select(
        "id,is_active",
      )
      .eq(
        "id",
        workspaceId,
      )
      .maybeSingle();

  if (
    error
  ) {
    console.error(
      "[CASE Budget Calendar] Failed to load workspace while reading calendar preferences.",
      {
        workspaceId,
        error,
      },
    );

    return {
      success:
        false,

      message:
        "CASE Budget could not load the active workspace.",
    };
  }

  const workspace =
    data as unknown as
      | WorkspaceRow
      | null;

  if (
    !workspace
  ) {
    return {
      success:
        false,

      message:
        "The active CASE Budget workspace could not be found.",
    };
  }

  if (
    !workspace.is_active
  ) {
    return {
      success:
        false,

      message:
        "Calendar preferences are unavailable because this workspace is inactive.",
    };
  }

  return {
    success:
      true,
  };
}

async function loadMembership({
  workspaceId,
  userId,
}: {
  workspaceId:
    string;

  userId:
    string;
}):
  Promise<
    | {
        success:
          true;
      }
    | {
        success:
          false;

        message:
          string;
      }
  > {
  const admin =
    createWorkspaceAdminClient();

  const {
    data,
    error,
  } =
    await admin
      .from(
        "workspace_members",
      )
      .select(
        "id,workspace_id,user_id,status",
      )
      .eq(
        "workspace_id",
        workspaceId,
      )
      .eq(
        "user_id",
        userId,
      )
      .maybeSingle();

  if (
    error
  ) {
    console.error(
      "[CASE Budget Calendar] Failed to verify membership while reading calendar preferences.",
      {
        workspaceId,
        userId,
        error,
      },
    );

    return {
      success:
        false,

      message:
        "CASE Budget could not verify your workspace access.",
    };
  }

  const membership =
    data as unknown as
      | MembershipRow
      | null;

  if (
    !membership ||
    membership.status !==
      "active"
  ) {
    return {
      success:
        false,

      message:
        "You do not have active access to calendar preferences in this workspace.",
    };
  }

  return {
    success:
      true,
  };
}

function createDefaultPreferences():
  FinancialCalendarPreferenceData {
  const now =
    new Date().toISOString();

  return {
    id:
      "",

    defaultView:
      "month",

    weekStartsOn:
      0,

    showWeekends:
      true,

    enableConflictDetection:
      true,

    filters:
      cloneDefaultFilters(),

    createdAt:
      now,

    updatedAt:
      now,
  };
}

function mapPreferenceRow({
  row,
  workspaceId,
  userId,
}: {
  row:
    CalendarPreferenceRow;

  workspaceId:
    string;

  userId:
    string;
}): FinancialCalendarPreferenceData | null {
  if (
    row.workspace_id !==
      workspaceId ||
    row.user_id !==
      userId
  ) {
    return null;
  }

  const id =
    normalizeRequiredText(
      row.id,
    );

  const defaultView =
    normalizeCalendarView(
      row.default_view,
    );

  const weekStartsOn =
    normalizeWeekday(
      row.week_starts_on,
    );

  const selectedDate =
    row.selected_date ===
      null
      ? null
      : normalizeDate(
          row.selected_date,
        );

  const filters =
    parsePersistentFilters(
      row.filters,
    );

  const createdAt =
    normalizeRequiredText(
      row.created_at,
    );

  const updatedAt =
    normalizeRequiredText(
      row.updated_at,
    );

  if (
    !id ||
    !defaultView ||
    weekStartsOn ===
      null ||
    (
      row.selected_date !==
        null &&
      selectedDate ===
        null
    ) ||
    !filters ||
    !createdAt ||
    !updatedAt
  ) {
    return null;
  }

  return {
    id,

    defaultView,

    weekStartsOn,

    showWeekends:
      row.show_weekends,

    enableConflictDetection:
      row.enable_conflict_detection,

    ...(selectedDate
      ? {
          selectedDate,
        }
      : {}),

    filters,

    createdAt,

    updatedAt,
  };
}

function parsePersistentFilters(
  value:
    Json,
): FinancialCalendarPersistentFilters | null {
  if (
    !isRecord(
      value,
    )
  ) {
    return null;
  }

  const search =
    typeof value.search ===
      "string"
      ? value.search
      : "";

  const eventTypes =
    parseEventTypes(
      value.eventTypes,
    );

  const statuses =
    parseStatuses(
      value.statuses,
    );

  const priorities =
    parsePriorities(
      value.priorities,
    );

  const accountIds =
    parseStringArray(
      value.accountIds,
    );

  if (
    eventTypes ===
      null ||
    statuses ===
      null ||
    priorities ===
      null ||
    accountIds ===
      null
  ) {
    return null;
  }

  return {
    search,

    eventTypes,

    statuses,

    priorities,

    accountIds,

    includeCompleted:
      readBoolean(
        value.includeCompleted,
        DEFAULT_FILTERS.includeCompleted,
      ),

    includeCanceled:
      readBoolean(
        value.includeCanceled,
        DEFAULT_FILTERS.includeCanceled,
      ),

    includeAutoGenerated:
      readBoolean(
        value.includeAutoGenerated,
        DEFAULT_FILTERS.includeAutoGenerated,
      ),

    includeManual:
      readBoolean(
        value.includeManual,
        DEFAULT_FILTERS.includeManual,
      ),
  };
}

function parseEventTypes(
  value:
    Json | undefined,
): FinancialCalendarEventType[] | null {
  if (
    value ===
      undefined
  ) {
    return [];
  }

  if (
    !Array.isArray(
      value,
    )
  ) {
    return null;
  }

  const result:
    FinancialCalendarEventType[] =
    [];

  for (
    const candidate of
      value
  ) {
    const normalized =
      normalizeEventType(
        candidate,
      );

    if (
      !normalized
    ) {
      return null;
    }

    if (
      !result.includes(
        normalized,
      )
    ) {
      result.push(
        normalized,
      );
    }
  }

  return result;
}

function parseStatuses(
  value:
    Json | undefined,
): FinancialCalendarEventStatus[] | null {
  if (
    value ===
      undefined
  ) {
    return [];
  }

  if (
    !Array.isArray(
      value,
    )
  ) {
    return null;
  }

  const result:
    FinancialCalendarEventStatus[] =
    [];

  for (
    const candidate of
      value
  ) {
    const normalized =
      normalizeEventStatus(
        candidate,
      );

    if (
      !normalized
    ) {
      return null;
    }

    if (
      !result.includes(
        normalized,
      )
    ) {
      result.push(
        normalized,
      );
    }
  }

  return result;
}

function parsePriorities(
  value:
    Json | undefined,
): FinancialCalendarEventPriority[] | null {
  if (
    value ===
      undefined
  ) {
    return [];
  }

  if (
    !Array.isArray(
      value,
    )
  ) {
    return null;
  }

  const result:
    FinancialCalendarEventPriority[] =
    [];

  for (
    const candidate of
      value
  ) {
    const normalized =
      normalizeEventPriority(
        candidate,
      );

    if (
      !normalized
    ) {
      return null;
    }

    if (
      !result.includes(
        normalized,
      )
    ) {
      result.push(
        normalized,
      );
    }
  }

  return result;
}

function parseStringArray(
  value:
    Json | undefined,
): string[] | null {
  if (
    value ===
      undefined
  ) {
    return [];
  }

  if (
    !Array.isArray(
      value,
    )
  ) {
    return null;
  }

  const result:
    string[] =
    [];

  for (
    const candidate of
      value
  ) {
    const normalized =
      normalizeRequiredText(
        candidate,
      );

    if (
      !normalized
    ) {
      return null;
    }

    if (
      !result.includes(
        normalized,
      )
    ) {
      result.push(
        normalized,
      );
    }
  }

  return result;
}

function normalizeCalendarView(
  value:
    unknown,
): FinancialCalendarView | null {
  switch (
    value
  ) {
    case "month":
    case "week":
    case "agenda":
      return value;

    default:
      return null;
  }
}

function normalizeWeekday(
  value:
    unknown,
): FinancialCalendarWeekday | null {
  switch (
    value
  ) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return value;

    default:
      return null;
  }
}

function normalizeEventType(
  value:
    unknown,
): FinancialCalendarEventType | null {
  switch (
    value
  ) {
    case "bill":
    case "paycheck":
    case "transaction":
    case "income":
    case "savings-contribution":
    case "debt-payment":
    case "transfer":
    case "reminder":
    case "custom":
      return value;

    default:
      return null;
  }
}

function normalizeEventStatus(
  value:
    unknown,
): FinancialCalendarEventStatus | null {
  switch (
    value
  ) {
    case "scheduled":
    case "due":
    case "past-due":
    case "pending":
    case "completed":
    case "skipped":
    case "canceled":
      return value;

    default:
      return null;
  }
}

function normalizeEventPriority(
  value:
    unknown,
): FinancialCalendarEventPriority | null {
  switch (
    value
  ) {
    case "critical":
    case "high":
    case "normal":
    case "low":
      return value;

    default:
      return null;
  }
}

function normalizeRequiredText(
  value:
    unknown,
): string | null {
  if (
    typeof value !==
      "string"
  ) {
    return null;
  }

  const normalized =
    value.trim();

  return normalized
    ? normalized
    : null;
}

function normalizeDate(
  value:
    unknown,
): string | null {
  const normalized =
    normalizeRequiredText(
      value,
    );

  if (
    !normalized ||
    !/^\d{4}-\d{2}-\d{2}$/.test(
      normalized,
    )
  ) {
    return null;
  }

  const date =
    new Date(
      `${normalized}T00:00:00.000Z`,
    );

  if (
    Number.isNaN(
      date.getTime(),
    )
  ) {
    return null;
  }

  return date
    .toISOString()
    .slice(
      0,
      10,
    ) ===
    normalized
    ? normalized
    : null;
}

function readBoolean(
  value:
    Json | undefined,
  fallback:
    boolean,
): boolean {
  return typeof value ===
    "boolean"
    ? value
    : fallback;
}

function cloneDefaultFilters():
  FinancialCalendarPersistentFilters {
  return {
    search:
      DEFAULT_FILTERS.search,

    eventTypes:
      [
        ...DEFAULT_FILTERS.eventTypes,
      ],

    statuses:
      [
        ...DEFAULT_FILTERS.statuses,
      ],

    priorities:
      [
        ...DEFAULT_FILTERS.priorities,
      ],

    accountIds:
      [
        ...DEFAULT_FILTERS.accountIds,
      ],

    includeCompleted:
      DEFAULT_FILTERS.includeCompleted,

    includeCanceled:
      DEFAULT_FILTERS.includeCanceled,

    includeAutoGenerated:
      DEFAULT_FILTERS.includeAutoGenerated,

    includeManual:
      DEFAULT_FILTERS.includeManual,
  };
}

function isRecord(
  value:
    unknown,
): value is Record<string, Json | undefined> {
  return Boolean(
    value &&
    typeof value ===
      "object" &&
    !Array.isArray(
      value,
    ),
  );
}

function getCalendarFeatureAccessMessage({
  reason,
  requiredPlan,
}: {
  reason:
    | "allowed"
    | "requires-plus"
    | "requires-pro"
    | "inactive-subscription";

  requiredPlan:
    | "free"
    | "plus"
    | "pro"
    | null;
}) {
  switch (
    reason
  ) {
    case "inactive-subscription":
      return "Calendar is unavailable because this workspace subscription is inactive. Please reactivate the subscription to continue.";

    case "requires-pro":
      return "Calendar requires the CASE Budget Pro plan for this workspace.";

    case "requires-plus":
      return "Calendar requires the CASE Budget Plus plan or higher for this workspace.";

    case "allowed":
    default: {
      if (
        requiredPlan ===
        "pro"
      ) {
        return "Calendar requires the CASE Budget Pro plan for this workspace.";
      }

      if (
        requiredPlan ===
        "plus"
      ) {
        return "Calendar requires the CASE Budget Plus plan or higher for this workspace.";
      }

      return "Calendar is not available for the current workspace subscription.";
    }
  }
}

function failure(
  message:
    string,
): GetFinancialCalendarPreferencesResult {
  return {
    success:
      false,

    error:
      message,
  };
}
