"use server";

import {
  revalidatePath,
} from "next/cache";

import {
  CaseBudgetServerAuthError,
  requireCaseBudgetServerAuth,
} from "@/lib/auth/server-auth";

import {
  createWorkspaceAdminClient,
} from "@/lib/supabase/admin";

import type {
  Json,
  WorkspaceMembershipStatusDatabaseEnum,
} from "@/types/database";

import type {
  FinancialCalendarEventPriority,
  FinancialCalendarEventStatus,
  FinancialCalendarEventType,
  FinancialCalendarPersistentFilters,
  FinancialCalendarPreferenceData,
  FinancialCalendarView,
  FinancialCalendarWeekday,
  UpdateFinancialCalendarPreferencesData,
  UpdateFinancialCalendarPreferencesResult,
} from "@/types/calendar";

const CALENDAR_PATH =
  "/dashboard/calendar";

type WorkspaceRow = {
  id:
    string;

  is_active:
    boolean;
};

type MembershipRow = {
  id:
    string;

  workspace_id:
    string;

  user_id:
    string;

  status:
    WorkspaceMembershipStatusDatabaseEnum;
};

type CalendarPreferenceRow = {
  id:
    string;

  workspace_id:
    string;

  user_id:
    string;

  default_view:
    string;

  week_starts_on:
    number;

  show_weekends:
    boolean;

  enable_conflict_detection:
    boolean;

  selected_date:
    string | null;

  filters:
    Json;

  created_at:
    string;

  updated_at:
    string;
};

type ValidatedCalendarPreferenceState = {
  defaultView:
    FinancialCalendarView;

  weekStartsOn:
    FinancialCalendarWeekday;

  showWeekends:
    boolean;

  enableConflictDetection:
    boolean;

  selectedDate:
    string | null;

  filters:
    FinancialCalendarPersistentFilters;
};

type PreferenceValidationResult =
  | {
      success:
        true;

      value:
        ValidatedCalendarPreferenceState;
    }
  | {
      success:
        false;

      fieldErrors:
        Partial<
          Record<
            keyof UpdateFinancialCalendarPreferencesData,
            string
          >
        >;
    };

const DEFAULT_FILTERS:
  FinancialCalendarPersistentFilters = {
    search:
      "",

    eventTypes:
      [],

    statuses:
      [],

    priorities:
      [],

    accountIds:
      [],

    includeCompleted:
      true,

    includeCanceled:
      false,

    includeAutoGenerated:
      true,

    includeManual:
      true,
  };

/**
 * Persists the authenticated user's Calendar preferences for the authenticated
 * active CASE Budget workspace.
 *
 * Production guarantees:
 *
 * - user_id and workspace_id are never accepted from the browser.
 * - the active workspace comes only from trusted server auth.
 * - the caller must have active membership in the workspace.
 * - preferences are user-scoped, so viewers may update their own preferences.
 * - the unique workspace_id + user_id constraint is the canonical identity.
 * - the action creates a preference row when none exists.
 * - the action updates the existing row when one exists.
 * - all persisted filters are validated and normalized before jsonb storage.
 * - selectedDate may be explicitly cleared with null.
 * - Supabase is the only persistence layer.
 * - no localStorage or sessionStorage is used.
 */
export async function updateCalendarPreferences(
  input:
    UpdateFinancialCalendarPreferencesData,
): Promise<UpdateFinancialCalendarPreferencesResult> {
  if (
    !input ||
    typeof input !==
      "object" ||
    Array.isArray(
      input,
    )
  ) {
    return failure(
      "Calendar preference changes are required.",
    );
  }

  try {
    const {
      userId,
      workspaceId,
    } =
      await requireCaseBudgetServerAuth();

    const workspaceResult =
      await loadWorkspace({
        workspaceId,
      });

    if (
      !workspaceResult.success
    ) {
      return failure(
        workspaceResult.message,
      );
    }

    const membershipResult =
      await loadMembership({
        workspaceId,
        userId,
      });

    if (
      !membershipResult.success
    ) {
      return failure(
        membershipResult.message,
      );
    }

    const existingResult =
      await loadExistingPreferences({
        workspaceId,
        userId,
      });

    if (
      !existingResult.success
    ) {
      return failure(
        existingResult.message,
      );
    }

    const existing =
      existingResult.row
        ? mapPreferenceRow({
            row:
              existingResult.row,
            workspaceId,
            userId,
          })
        : createDefaultPreferences();

    if (
      !existing
    ) {
      return failure(
        "CASE Budget could not read your existing calendar preferences.",
      );
    }

    const validation =
      validateMergedPreferences({
        existing,
        updates:
          input,
      });

    if (
      !validation.success
    ) {
      return {
        success:
          false,

        error:
          "Review the calendar preferences and try again.",

        fieldErrors:
          validation.fieldErrors,
      };
    }

    const value =
      validation.value;

    const now =
      new Date().toISOString();

    const admin =
      createWorkspaceAdminClient();

    let savedRow:
      CalendarPreferenceRow | null =
      null;

    if (
      existingResult.row
    ) {
      const {
        data,
        error,
      } =
        await admin
          .from(
            "case_budget_calendar_preferences",
          )
          .update({
            default_view:
              value.defaultView,

            week_starts_on:
              value.weekStartsOn,

            show_weekends:
              value.showWeekends,

            enable_conflict_detection:
              value.enableConflictDetection,

            selected_date:
              value.selectedDate,

            filters:
              toJson(
                value.filters,
              ),

            updated_at:
              now,
          })
          .eq(
            "id",
            existingResult.row.id,
          )
          .eq(
            "workspace_id",
            workspaceId,
          )
          .eq(
            "user_id",
            userId,
          )
          .eq(
            "updated_at",
            existingResult.row.updated_at,
          )
          .select(
            "id,workspace_id,user_id,default_view,week_starts_on,show_weekends,enable_conflict_detection,selected_date,filters,created_at,updated_at",
          )
          .maybeSingle();

      if (
        error
      ) {
        console.error(
          "[CASE Budget Calendar] Failed to update calendar preferences.",
          {
            workspaceId,
            userId,
            error,
          },
        );

        return failure(
          "CASE Budget could not update your calendar preferences.",
        );
      }

      if (
        !data
      ) {
        return failure(
          await determinePreferenceConflict({
            workspaceId,
            userId,
            expectedUpdatedAt:
              existingResult.row.updated_at,
          }),
        );
      }

      savedRow =
        data as unknown as
          CalendarPreferenceRow;
    } else {
      const {
        data,
        error,
      } =
        await admin
          .from(
            "case_budget_calendar_preferences",
          )
          .insert({
            workspace_id:
              workspaceId,

            user_id:
              userId,

            default_view:
              value.defaultView,

            week_starts_on:
              value.weekStartsOn,

            show_weekends:
              value.showWeekends,

            enable_conflict_detection:
              value.enableConflictDetection,

            selected_date:
              value.selectedDate,

            filters:
              toJson(
                value.filters,
              ),

            created_at:
              now,

            updated_at:
              now,
          })
          .select(
            "id,workspace_id,user_id,default_view,week_starts_on,show_weekends,enable_conflict_detection,selected_date,filters,created_at,updated_at",
          )
          .single();

      if (
        error
      ) {
        /**
         * Another request may have created the unique workspace/user row after
         * our read. Re-read once and apply the requested state through the
         * update path rather than surfacing a false failure.
         */
        const retryResult =
          await updateAfterConcurrentInsert({
            workspaceId,
            userId,
            value,
            now,
          });

        if (
          !retryResult.success
        ) {
          console.error(
            "[CASE Budget Calendar] Failed to create calendar preferences.",
            {
              workspaceId,
              userId,
              error,
            },
          );

          return failure(
            retryResult.message,
          );
        }

        savedRow =
          retryResult.row;
      } else {
        savedRow =
          data as unknown as
            CalendarPreferenceRow;
      }
    }

    const preferences =
      mapPreferenceRow({
        row:
          savedRow,
        workspaceId,
        userId,
      });

    if (
      !preferences
    ) {
      return failure(
        "Your calendar preferences were saved, but CASE Budget could not read the stored record.",
      );
    }

    revalidatePath(
      CALENDAR_PATH,
    );

    return {
      success:
        true,

      preferences,
    };
  } catch (
    error
  ) {
    if (
      error instanceof
      CaseBudgetServerAuthError
    ) {
      return failure(
        error.message,
      );
    }

    console.error(
      "[CASE Budget Calendar] Unexpected update-calendar-preferences error.",
      error,
    );

    return failure(
      "CASE Budget could not update your calendar preferences. Please try again.",
    );
  }
}

async function loadWorkspace({
  workspaceId,
}: {
  workspaceId:
    string;
}):
  Promise<
    | {
        success:
          true;
      }
    | {
        success:
          false;

        message:
          string;
      }
  > {
  const admin =
    createWorkspaceAdminClient();

  const {
    data,
    error,
  } =
    await admin
      .from(
        "workspaces",
      )
      .select(
        "id,is_active",
      )
      .eq(
        "id",
        workspaceId,
      )
      .maybeSingle();

  if (
    error
  ) {
    console.error(
      "[CASE Budget Calendar] Failed to load workspace while updating calendar preferences.",
      {
        workspaceId,
        error,
      },
    );

    return {
      success:
        false,

      message:
        "CASE Budget could not load the active workspace.",
    };
  }

  const workspace =
    data as unknown as
      | WorkspaceRow
      | null;

  if (
    !workspace
  ) {
    return {
      success:
        false,

      message:
        "The active CASE Budget workspace could not be found.",
    };
  }

  if (
    !workspace.is_active
  ) {
    return {
      success:
        false,

      message:
        "Calendar preferences cannot be changed because this workspace is inactive.",
    };
  }

  return {
    success:
      true,
  };
}

async function loadMembership({
  workspaceId,
  userId,
}: {
  workspaceId:
    string;

  userId:
    string;
}):
  Promise<
    | {
        success:
          true;
      }
    | {
        success:
          false;

        message:
          string;
      }
  > {
  const admin =
    createWorkspaceAdminClient();

  const {
    data,
    error,
  } =
    await admin
      .from(
        "workspace_members",
      )
      .select(
        "id,workspace_id,user_id,status",
      )
      .eq(
        "workspace_id",
        workspaceId,
      )
      .eq(
        "user_id",
        userId,
      )
      .maybeSingle();

  if (
    error
  ) {
    console.error(
      "[CASE Budget Calendar] Failed to verify membership while updating calendar preferences.",
      {
        workspaceId,
        userId,
        error,
      },
    );

    return {
      success:
        false,

      message:
        "CASE Budget could not verify your workspace access.",
    };
  }

  const membership =
    data as unknown as
      | MembershipRow
      | null;

  if (
    !membership ||
    membership.status !==
      "active"
  ) {
    return {
      success:
        false,

      message:
        "You do not have active access to calendar preferences in this workspace.",
    };
  }

  return {
    success:
      true,
  };
}

async function loadExistingPreferences({
  workspaceId,
  userId,
}: {
  workspaceId:
    string;

  userId:
    string;
}):
  Promise<
    | {
        success:
          true;

        row:
          CalendarPreferenceRow | null;
      }
    | {
        success:
          false;

        message:
          string;
      }
  > {
  const admin =
    createWorkspaceAdminClient();

  const {
    data,
    error,
  } =
    await admin
      .from(
        "case_budget_calendar_preferences",
      )
      .select(
        "id,workspace_id,user_id,default_view,week_starts_on,show_weekends,enable_conflict_detection,selected_date,filters,created_at,updated_at",
      )
      .eq(
        "workspace_id",
        workspaceId,
      )
      .eq(
        "user_id",
        userId,
      )
      .maybeSingle();

  if (
    error
  ) {
    console.error(
      "[CASE Budget Calendar] Failed to load existing calendar preferences before update.",
      {
        workspaceId,
        userId,
        error,
      },
    );

    return {
      success:
        false,

      message:
        "CASE Budget could not load your existing calendar preferences.",
    };
  }

  return {
    success:
      true,

    row:
      data as unknown as
        | CalendarPreferenceRow
        | null,
  };
}

async function updateAfterConcurrentInsert({
  workspaceId,
  userId,
  value,
  now,
}: {
  workspaceId:
    string;

  userId:
    string;

  value:
    ValidatedCalendarPreferenceState;

  now:
    string;
}):
  Promise<
    | {
        success:
          true;

        row:
          CalendarPreferenceRow;
      }
    | {
        success:
          false;

        message:
          string;
      }
  > {
  const admin =
    createWorkspaceAdminClient();

  const {
    data:
      existingData,
    error:
      existingError,
  } =
    await admin
      .from(
        "case_budget_calendar_preferences",
      )
      .select(
        "id,workspace_id,user_id,default_view,week_starts_on,show_weekends,enable_conflict_detection,selected_date,filters,created_at,updated_at",
      )
      .eq(
        "workspace_id",
        workspaceId,
      )
      .eq(
        "user_id",
        userId,
      )
      .maybeSingle();

  if (
    existingError ||
    !existingData
  ) {
    return {
      success:
        false,

      message:
        "CASE Budget could not create your calendar preferences.",
    };
  }

  const existingRow =
    existingData as unknown as
      CalendarPreferenceRow;

  const {
    data,
    error,
  } =
    await admin
      .from(
        "case_budget_calendar_preferences",
      )
      .update({
        default_view:
          value.defaultView,

        week_starts_on:
          value.weekStartsOn,

        show_weekends:
          value.showWeekends,

        enable_conflict_detection:
          value.enableConflictDetection,

        selected_date:
          value.selectedDate,

        filters:
          toJson(
            value.filters,
          ),

        updated_at:
          now,
      })
      .eq(
        "id",
        existingRow.id,
      )
      .eq(
        "workspace_id",
        workspaceId,
      )
      .eq(
        "user_id",
        userId,
      )
      .eq(
        "updated_at",
        existingRow.updated_at,
      )
      .select(
        "id,workspace_id,user_id,default_view,week_starts_on,show_weekends,enable_conflict_detection,selected_date,filters,created_at,updated_at",
      )
      .maybeSingle();

  if (
    error ||
    !data
  ) {
    return {
      success:
        false,

      message:
        "Your calendar preferences changed while they were being saved. Please try again.",
    };
  }

  return {
    success:
      true,

    row:
      data as unknown as
        CalendarPreferenceRow,
  };
}

async function determinePreferenceConflict({
  workspaceId,
  userId,
  expectedUpdatedAt,
}: {
  workspaceId:
    string;

  userId:
    string;

  expectedUpdatedAt:
    string;
}): Promise<string> {
  const admin =
    createWorkspaceAdminClient();

  const {
    data,
    error,
  } =
    await admin
      .from(
        "case_budget_calendar_preferences",
      )
      .select(
        "id,updated_at",
      )
      .eq(
        "workspace_id",
        workspaceId,
      )
      .eq(
        "user_id",
        userId,
      )
      .maybeSingle();

  if (
    error
  ) {
    return "CASE Budget could not update your calendar preferences. Refresh and try again.";
  }

  const current =
    data as unknown as
      | {
          id:
            string;

          updated_at:
            string;
        }
      | null;

  if (
    !current
  ) {
    return "Your calendar preference record no longer exists. Try saving again.";
  }

  if (
    current.updated_at !==
    expectedUpdatedAt
  ) {
    return "Your calendar preferences changed while you were editing them. Refresh and try again.";
  }

  return "CASE Budget could not update your calendar preferences. Refresh and try again.";
}

function validateMergedPreferences({
  existing,
  updates,
}: {
  existing:
    FinancialCalendarPreferenceData;

  updates:
    UpdateFinancialCalendarPreferencesData;
}): PreferenceValidationResult {
  const fieldErrors:
    Partial<
      Record<
        keyof UpdateFinancialCalendarPreferencesData,
        string
      >
    > = {};

  const defaultView =
    hasOwn(
      updates,
      "defaultView",
    )
      ? normalizeCalendarView(
          updates.defaultView,
        )
      : existing.defaultView;

  if (
    !defaultView
  ) {
    fieldErrors.defaultView =
      "Select a valid default calendar view.";
  }

  const weekStartsOn =
    hasOwn(
      updates,
      "weekStartsOn",
    )
      ? normalizeWeekday(
          updates.weekStartsOn,
        )
      : existing.weekStartsOn;

  if (
    weekStartsOn ===
      null
  ) {
    fieldErrors.weekStartsOn =
      "Select a valid first day of the week.";
  }

  const showWeekends =
    hasOwn(
      updates,
      "showWeekends",
    )
      ? normalizeBoolean(
          updates.showWeekends,
        )
      : existing.showWeekends;

  if (
    showWeekends ===
      null
  ) {
    fieldErrors.showWeekends =
      "Weekend visibility must be true or false.";
  }

  const enableConflictDetection =
    hasOwn(
      updates,
      "enableConflictDetection",
    )
      ? normalizeBoolean(
          updates.enableConflictDetection,
        )
      : existing.enableConflictDetection;

  if (
    enableConflictDetection ===
      null
  ) {
    fieldErrors.enableConflictDetection =
      "Conflict detection must be true or false.";
  }

  let selectedDate:
    string | null =
    existing.selectedDate ??
    null;

  if (
    hasOwn(
      updates,
      "selectedDate",
    )
  ) {
    if (
      updates.selectedDate ===
        null ||
      updates.selectedDate ===
        undefined ||
      updates.selectedDate ===
        ""
    ) {
      selectedDate =
        null;
    } else {
      selectedDate =
        normalizeDate(
          updates.selectedDate,
        );

      if (
        selectedDate ===
          null
      ) {
        fieldErrors.selectedDate =
          "Choose a valid selected calendar date.";
      }
    }
  }

  const filters =
    hasOwn(
      updates,
      "filters",
    )
      ? validatePersistentFilters(
          updates.filters,
        )
      : {
          success:
            true as const,

          value:
            cloneFilters(
              existing.filters,
            ),
        };

  if (
    !filters.success
  ) {
    fieldErrors.filters =
      filters.message;
  }

  if (
    Object.keys(
      fieldErrors,
    ).length >
      0 ||
    !defaultView ||
    weekStartsOn ===
      null ||
    showWeekends ===
      null ||
    enableConflictDetection ===
      null ||
    !filters.success
  ) {
    return {
      success:
        false,

      fieldErrors,
    };
  }

  return {
    success:
      true,

    value: {
      defaultView,

      weekStartsOn,

      showWeekends,

      enableConflictDetection,

      selectedDate,

      filters:
        filters.value,
    },
  };
}

function validatePersistentFilters(
  filters:
    FinancialCalendarPersistentFilters | undefined,
):
  | {
      success:
        true;

      value:
        FinancialCalendarPersistentFilters;
    }
  | {
      success:
        false;

      message:
        string;
    } {
  if (
    !filters ||
    typeof filters !==
      "object" ||
    Array.isArray(
      filters,
    )
  ) {
    return {
      success:
        false,

      message:
        "Calendar filters are invalid.",
    };
  }

  const search =
    typeof filters.search ===
      "string"
      ? filters.search.trim()
      : "";

  if (
    search.length >
      200
  ) {
    return {
      success:
        false,

      message:
        "Calendar filter search must be 200 characters or fewer.",
    };
  }

  const eventTypes =
    normalizeEventTypeArray(
      filters.eventTypes,
    );

  const statuses =
    normalizeStatusArray(
      filters.statuses,
    );

  const priorities =
    normalizePriorityArray(
      filters.priorities,
    );

  const accountIds =
    normalizeStringArray(
      filters.accountIds,
    );

  if (
    eventTypes ===
      null ||
    statuses ===
      null ||
    priorities ===
      null ||
    accountIds ===
      null ||
    typeof filters.includeCompleted !==
      "boolean" ||
    typeof filters.includeCanceled !==
      "boolean" ||
    typeof filters.includeAutoGenerated !==
      "boolean" ||
    typeof filters.includeManual !==
      "boolean"
  ) {
    return {
      success:
        false,

      message:
        "One or more Calendar filter values are invalid.",
    };
  }

  return {
    success:
      true,

    value: {
      search,

      eventTypes,

      statuses,

      priorities,

      accountIds,

      includeCompleted:
        filters.includeCompleted,

      includeCanceled:
        filters.includeCanceled,

      includeAutoGenerated:
        filters.includeAutoGenerated,

      includeManual:
        filters.includeManual,
    },
  };
}

function createDefaultPreferences():
  FinancialCalendarPreferenceData {
  const now =
    new Date().toISOString();

  return {
    id:
      "",

    defaultView:
      "month",

    weekStartsOn:
      0,

    showWeekends:
      true,

    enableConflictDetection:
      true,

    filters:
      cloneFilters(
        DEFAULT_FILTERS,
      ),

    createdAt:
      now,

    updatedAt:
      now,
  };
}

function mapPreferenceRow({
  row,
  workspaceId,
  userId,
}: {
  row:
    CalendarPreferenceRow;

  workspaceId:
    string;

  userId:
    string;
}): FinancialCalendarPreferenceData | null {
  if (
    row.workspace_id !==
      workspaceId ||
    row.user_id !==
      userId
  ) {
    return null;
  }

  const id =
    normalizeRequiredText(
      row.id,
    );

  const defaultView =
    normalizeCalendarView(
      row.default_view,
    );

  const weekStartsOn =
    normalizeWeekday(
      row.week_starts_on,
    );

  const selectedDate =
    row.selected_date ===
      null
      ? null
      : normalizeDate(
          row.selected_date,
        );

  const filters =
    parsePersistentFiltersJson(
      row.filters,
    );

  const createdAt =
    normalizeRequiredText(
      row.created_at,
    );

  const updatedAt =
    normalizeRequiredText(
      row.updated_at,
    );

  if (
    !id ||
    !defaultView ||
    weekStartsOn ===
      null ||
    (
      row.selected_date !==
        null &&
      selectedDate ===
        null
    ) ||
    !filters ||
    !createdAt ||
    !updatedAt
  ) {
    return null;
  }

  return {
    id,

    defaultView,

    weekStartsOn,

    showWeekends:
      row.show_weekends,

    enableConflictDetection:
      row.enable_conflict_detection,

    ...(selectedDate
      ? {
          selectedDate,
        }
      : {}),

    filters,

    createdAt,

    updatedAt,
  };
}

function parsePersistentFiltersJson(
  value:
    Json,
): FinancialCalendarPersistentFilters | null {
  if (
    !isRecord(
      value,
    )
  ) {
    return null;
  }

  const eventTypes =
    parseEventTypesJson(
      value.eventTypes,
    );

  const statuses =
    parseStatusesJson(
      value.statuses,
    );

  const priorities =
    parsePrioritiesJson(
      value.priorities,
    );

  const accountIds =
    parseStringArrayJson(
      value.accountIds,
    );

  if (
    eventTypes ===
      null ||
    statuses ===
      null ||
    priorities ===
      null ||
    accountIds ===
      null
  ) {
    return null;
  }

  return {
    search:
      typeof value.search ===
        "string"
        ? value.search
        : "",

    eventTypes,

    statuses,

    priorities,

    accountIds,

    includeCompleted:
      readBoolean(
        value.includeCompleted,
        DEFAULT_FILTERS.includeCompleted,
      ),

    includeCanceled:
      readBoolean(
        value.includeCanceled,
        DEFAULT_FILTERS.includeCanceled,
      ),

    includeAutoGenerated:
      readBoolean(
        value.includeAutoGenerated,
        DEFAULT_FILTERS.includeAutoGenerated,
      ),

    includeManual:
      readBoolean(
        value.includeManual,
        DEFAULT_FILTERS.includeManual,
      ),
  };
}

function normalizeCalendarView(
  value:
    unknown,
): FinancialCalendarView | null {
  switch (
    value
  ) {
    case "month":
    case "week":
    case "agenda":
      return value;

    default:
      return null;
  }
}

function normalizeWeekday(
  value:
    unknown,
): FinancialCalendarWeekday | null {
  switch (
    value
  ) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return value;

    default:
      return null;
  }
}

function normalizeEventType(
  value:
    unknown,
): FinancialCalendarEventType | null {
  switch (
    value
  ) {
    case "bill":
    case "paycheck":
    case "transaction":
    case "income":
    case "savings-contribution":
    case "debt-payment":
    case "transfer":
    case "reminder":
    case "custom":
      return value;

    default:
      return null;
  }
}

function normalizeEventStatus(
  value:
    unknown,
): FinancialCalendarEventStatus | null {
  switch (
    value
  ) {
    case "scheduled":
    case "due":
    case "past-due":
    case "pending":
    case "completed":
    case "skipped":
    case "canceled":
      return value;

    default:
      return null;
  }
}

function normalizeEventPriority(
  value:
    unknown,
): FinancialCalendarEventPriority | null {
  switch (
    value
  ) {
    case "critical":
    case "high":
    case "normal":
    case "low":
      return value;

    default:
      return null;
  }
}

function normalizeEventTypeArray(
  value:
    unknown,
): FinancialCalendarEventType[] | null {
  if (
    !Array.isArray(
      value,
    )
  ) {
    return null;
  }

  const result:
    FinancialCalendarEventType[] =
    [];

  for (
    const candidate of
      value
  ) {
    const normalized =
      normalizeEventType(
        candidate,
      );

    if (
      !normalized
    ) {
      return null;
    }

    if (
      !result.includes(
        normalized,
      )
    ) {
      result.push(
        normalized,
      );
    }
  }

  return result;
}

function normalizeStatusArray(
  value:
    unknown,
): FinancialCalendarEventStatus[] | null {
  if (
    !Array.isArray(
      value,
    )
  ) {
    return null;
  }

  const result:
    FinancialCalendarEventStatus[] =
    [];

  for (
    const candidate of
      value
  ) {
    const normalized =
      normalizeEventStatus(
        candidate,
      );

    if (
      !normalized
    ) {
      return null;
    }

    if (
      !result.includes(
        normalized,
      )
    ) {
      result.push(
        normalized,
      );
    }
  }

  return result;
}

function normalizePriorityArray(
  value:
    unknown,
): FinancialCalendarEventPriority[] | null {
  if (
    !Array.isArray(
      value,
    )
  ) {
    return null;
  }

  const result:
    FinancialCalendarEventPriority[] =
    [];

  for (
    const candidate of
      value
  ) {
    const normalized =
      normalizeEventPriority(
        candidate,
      );

    if (
      !normalized
    ) {
      return null;
    }

    if (
      !result.includes(
        normalized,
      )
    ) {
      result.push(
        normalized,
      );
    }
  }

  return result;
}

function normalizeStringArray(
  value:
    unknown,
): string[] | null {
  if (
    !Array.isArray(
      value,
    )
  ) {
    return null;
  }

  const result:
    string[] =
    [];

  for (
    const candidate of
      value
  ) {
    const normalized =
      normalizeRequiredText(
        candidate,
      );

    if (
      !normalized
    ) {
      return null;
    }

    if (
      !result.includes(
        normalized,
      )
    ) {
      result.push(
        normalized,
      );
    }
  }

  return result;
}

function parseEventTypesJson(
  value:
    Json | undefined,
): FinancialCalendarEventType[] | null {
  if (
    value ===
      undefined
  ) {
    return [];
  }

  return normalizeEventTypeArray(
    value,
  );
}

function parseStatusesJson(
  value:
    Json | undefined,
): FinancialCalendarEventStatus[] | null {
  if (
    value ===
      undefined
  ) {
    return [];
  }

  return normalizeStatusArray(
    value,
  );
}

function parsePrioritiesJson(
  value:
    Json | undefined,
): FinancialCalendarEventPriority[] | null {
  if (
    value ===
      undefined
  ) {
    return [];
  }

  return normalizePriorityArray(
    value,
  );
}

function parseStringArrayJson(
  value:
    Json | undefined,
): string[] | null {
  if (
    value ===
      undefined
  ) {
    return [];
  }

  return normalizeStringArray(
    value,
  );
}

function normalizeBoolean(
  value:
    unknown,
): boolean | null {
  return typeof value ===
    "boolean"
    ? value
    : null;
}

function normalizeRequiredText(
  value:
    unknown,
): string | null {
  if (
    typeof value !==
      "string"
  ) {
    return null;
  }

  const normalized =
    value.trim();

  return normalized
    ? normalized
    : null;
}

function normalizeDate(
  value:
    unknown,
): string | null {
  const normalized =
    normalizeRequiredText(
      value,
    );

  if (
    !normalized ||
    !/^\d{4}-\d{2}-\d{2}$/.test(
      normalized,
    )
  ) {
    return null;
  }

  const date =
    new Date(
      `${normalized}T00:00:00.000Z`,
    );

  if (
    Number.isNaN(
      date.getTime(),
    )
  ) {
    return null;
  }

  return date
    .toISOString()
    .slice(
      0,
      10,
    ) ===
    normalized
    ? normalized
    : null;
}

function readBoolean(
  value:
    Json | undefined,
  fallback:
    boolean,
): boolean {
  return typeof value ===
    "boolean"
    ? value
    : fallback;
}

function cloneFilters(
  filters:
    FinancialCalendarPersistentFilters,
): FinancialCalendarPersistentFilters {
  return {
    search:
      filters.search,

    eventTypes:
      [
        ...filters.eventTypes,
      ],

    statuses:
      [
        ...filters.statuses,
      ],

    priorities:
      [
        ...filters.priorities,
      ],

    accountIds:
      [
        ...filters.accountIds,
      ],

    includeCompleted:
      filters.includeCompleted,

    includeCanceled:
      filters.includeCanceled,

    includeAutoGenerated:
      filters.includeAutoGenerated,

    includeManual:
      filters.includeManual,
  };
}

function hasOwn(
  value:
    object,
  key:
    PropertyKey,
): boolean {
  return Object.prototype.hasOwnProperty.call(
    value,
    key,
  );
}

function toJson(
  value:
    unknown,
): Json {
  return JSON.parse(
    JSON.stringify(
      value,
    ),
  ) as Json;
}

function isRecord(
  value:
    unknown,
): value is Record<string, Json | undefined> {
  return Boolean(
    value &&
    typeof value ===
      "object" &&
    !Array.isArray(
      value,
    ),
  );
}

function failure(
  message:
    string,
): UpdateFinancialCalendarPreferencesResult {
  return {
    success:
      false,

    error:
      message,
  };
}
