import type {
  FinancialCalendarAgendaGroup,
  FinancialCalendarConflict,
  FinancialCalendarDateRange,
  FinancialCalendarDay,
  FinancialCalendarEvent,
  FinancialCalendarEventOccurrence,
  FinancialCalendarFilters,
  FinancialCalendarMonth,
  FinancialCalendarPreferences,
  FinancialCalendarRecurrenceRule,
  FinancialCalendarSummary,
  FinancialCalendarView,
  FinancialCalendarWeek,
  FinancialCalendarWeekday,
} from "@/types/calendar";

const MILLISECONDS_PER_DAY =
  86_400_000;

export const DEFAULT_CALENDAR_PREFERENCES:
  FinancialCalendarPreferences = {
    defaultView:
      "month",

    weekStartsOn:
      0,

    showWeekends:
      true,

    showBills:
      true,
    showPaychecks:
      true,
    showTransactions:
      true,
    showSavingsContributions:
      true,
    showDebtPayments:
      true,
    showTransfers:
      true,
    showReminders:
      true,
    showCustomEvents:
      true,

    showCompletedEvents:
      true,
    showCanceledEvents:
      false,

    enableConflictDetection:
      true,

    defaultReminderAmount:
      1,
    defaultReminderUnit:
      "day",
  };

export const DEFAULT_CALENDAR_FILTERS:
  FinancialCalendarFilters = {
    search:
      "",

    eventTypes:
      [],

    statuses:
      [],

    priorities:
      [],

    accountIds:
      [],

    includeCompleted:
      true,
    includeCanceled:
      false,
    includeAutoGenerated:
      true,
    includeManual:
      true,
  };

export function normalizeCalendarDate(
  value: string | Date,
) {
  if (
    value instanceof
    Date
  ) {
    return formatDateKey(
      value,
    );
  }

  const normalizedValue =
    value.slice(
      0,
      10,
    );

  const date =
    parseDateKey(
      normalizedValue,
    );

  if (
    Number.isNaN(
      date.getTime(),
    )
  ) {
    return formatDateKey(
      new Date(),
    );
  }

  return normalizedValue;
}

export function parseDateKey(
  value: string,
) {
  const [
    year,
    month,
    day,
  ] =
    value
      .slice(
        0,
        10,
      )
      .split(
        "-",
      )
      .map(
        Number,
      );

  if (
    !Number.isInteger(
      year,
    ) ||
    !Number.isInteger(
      month,
    ) ||
    !Number.isInteger(
      day,
    )
  ) {
    return new Date(
      Number.NaN,
    );
  }

  return new Date(
    year,
    month -
      1,
    day,
  );
}

export function formatDateKey(
  value: Date,
) {
  const year =
    value.getFullYear();

  const month =
    String(
      value.getMonth() +
        1,
    ).padStart(
      2,
      "0",
    );

  const day =
    String(
      value.getDate(),
    ).padStart(
      2,
      "0",
    );

  return `${year}-${month}-${day}`;
}

export function addCalendarDays(
  value: string,
  amount: number,
) {
  const date =
    parseDateKey(
      value,
    );

  date.setDate(
    date.getDate() +
      amount,
  );

  return formatDateKey(
    date,
  );
}

export function addCalendarWeeks(
  value: string,
  amount: number,
) {
  return addCalendarDays(
    value,
    amount *
      7,
  );
}

export function addCalendarMonths(
  value: string,
  amount: number,
) {
  const date =
    parseDateKey(
      value,
    );

  const originalDay =
    date.getDate();

  date.setDate(
    1,
  );

  date.setMonth(
    date.getMonth() +
      amount,
  );

  const lastDay =
    getLastDayOfMonth(
      date.getFullYear(),
      date.getMonth() +
        1,
    );

  date.setDate(
    Math.min(
      originalDay,
      lastDay,
    ),
  );

  return formatDateKey(
    date,
  );
}

export function addCalendarYears(
  value: string,
  amount: number,
) {
  const date =
    parseDateKey(
      value,
    );

  const month =
    date.getMonth();

  const day =
    date.getDate();

  date.setDate(
    1,
  );

  date.setFullYear(
    date.getFullYear() +
      amount,
  );

  date.setMonth(
    month,
  );

  date.setDate(
    Math.min(
      day,
      getLastDayOfMonth(
        date.getFullYear(),
        month +
          1,
      ),
    ),
  );

  return formatDateKey(
    date,
  );
}

export function differenceInCalendarDays(
  startDate: string,
  endDate: string,
) {
  const start =
    parseDateKey(
      startDate,
    );

  const end =
    parseDateKey(
      endDate,
    );

  return Math.round(
    (
      end.getTime() -
      start.getTime()
    ) /
      MILLISECONDS_PER_DAY,
  );
}

export function compareCalendarDates(
  firstDate: string,
  secondDate: string,
) {
  return normalizeCalendarDate(
    firstDate,
  ).localeCompare(
    normalizeCalendarDate(
      secondDate,
    ),
  );
}

export function isDateWithinRange(
  date: string,
  range:
    FinancialCalendarDateRange,
) {
  const normalizedDate =
    normalizeCalendarDate(
      date,
    );

  return (
    normalizedDate >=
      normalizeCalendarDate(
        range.startDate,
      ) &&
    normalizedDate <=
      normalizeCalendarDate(
        range.endDate,
      )
  );
}

export function getStartOfWeek(
  value: string,
  weekStartsOn:
    FinancialCalendarWeekday = 0,
) {
  const date =
    parseDateKey(
      value,
    );

  const day =
    date.getDay();

  const difference =
    (
      day -
      weekStartsOn +
      7
    ) %
    7;

  date.setDate(
    date.getDate() -
      difference,
  );

  return formatDateKey(
    date,
  );
}

export function getEndOfWeek(
  value: string,
  weekStartsOn:
    FinancialCalendarWeekday = 0,
) {
  return addCalendarDays(
    getStartOfWeek(
      value,
      weekStartsOn,
    ),
    6,
  );
}

export function getStartOfMonth(
  value: string,
) {
  const date =
    parseDateKey(
      value,
    );

  return formatDateKey(
    new Date(
      date.getFullYear(),
      date.getMonth(),
      1,
    ),
  );
}

export function getEndOfMonth(
  value: string,
) {
  const date =
    parseDateKey(
      value,
    );

  return formatDateKey(
    new Date(
      date.getFullYear(),
      date.getMonth() +
        1,
      0,
    ),
  );
}

export function getCalendarVisibleRange({
  selectedDate,
  view,
  weekStartsOn,
}: {
  selectedDate: string;
  view:
    FinancialCalendarView;
  weekStartsOn:
    FinancialCalendarWeekday;
}): FinancialCalendarDateRange {
  if (
    view ===
    "week"
  ) {
    return {
      startDate:
        getStartOfWeek(
          selectedDate,
          weekStartsOn,
        ),
      endDate:
        getEndOfWeek(
          selectedDate,
          weekStartsOn,
        ),
    };
  }

  if (
    view ===
    "agenda"
  ) {
    return {
      startDate:
        selectedDate,
      endDate:
        addCalendarDays(
          selectedDate,
          30,
        ),
    };
  }

  const monthStart =
    getStartOfMonth(
      selectedDate,
    );

  const monthEnd =
    getEndOfMonth(
      selectedDate,
    );

  return {
    startDate:
      getStartOfWeek(
        monthStart,
        weekStartsOn,
      ),
    endDate:
      getEndOfWeek(
        monthEnd,
        weekStartsOn,
      ),
  };
}

export function buildCalendarMonth({
  selectedDate,
  occurrences,
  weekStartsOn = 0,
  showWeekends = true,
  today = formatDateKey(
    new Date(),
  ),
}: {
  selectedDate: string;
  occurrences:
    FinancialCalendarEventOccurrence[];
  weekStartsOn?:
    FinancialCalendarWeekday;
  showWeekends?: boolean;
  today?: string;
}): FinancialCalendarMonth {
  const normalizedSelectedDate =
    normalizeCalendarDate(
      selectedDate,
    );

  const selectedDateObject =
    parseDateKey(
      normalizedSelectedDate,
    );

  const month =
    selectedDateObject.getMonth() +
    1;

  const year =
    selectedDateObject.getFullYear();

  const monthStart =
    getStartOfMonth(
      normalizedSelectedDate,
    );

  const monthEnd =
    getEndOfMonth(
      normalizedSelectedDate,
    );

  const visibleStart =
    getStartOfWeek(
      monthStart,
      weekStartsOn,
    );

  const visibleEnd =
    getEndOfWeek(
      monthEnd,
      weekStartsOn,
    );

  const days:
    FinancialCalendarDay[] = [];

  let currentDate =
    visibleStart;

  while (
    currentDate <=
    visibleEnd
  ) {
    const currentDateObject =
      parseDateKey(
        currentDate,
      );

    const isWeekend =
      currentDateObject.getDay() ===
        0 ||
      currentDateObject.getDay() ===
        6;

    if (
      showWeekends ||
      !isWeekend
    ) {
      days.push(
        buildCalendarDay({
          date:
            currentDate,
          selectedDate:
            normalizedSelectedDate,
          month,
          today,
          occurrences,
        }),
      );
    }

    currentDate =
      addCalendarDays(
        currentDate,
        1,
      );
  }

  const daysPerWeek =
    showWeekends
      ? 7
      : 5;

  const weeks:
    FinancialCalendarWeek[] = [];

  for (
    let index = 0;
    index <
    days.length;
    index +=
      daysPerWeek
  ) {
    const weekDays =
      days.slice(
        index,
        index +
          daysPerWeek,
      );

    if (
      weekDays.length ===
      0
    ) {
      continue;
    }

    weeks.push({
      id:
        `calendar-week-${weekDays[0].date}`,
      startDate:
        weekDays[0].date,
      endDate:
        weekDays[
          weekDays.length -
            1
        ].date,
      days:
        weekDays,
    });
  }

  return {
    month,
    year,
    startDate:
      visibleStart,
    endDate:
      visibleEnd,
    weeks,
  };
}

export function buildCalendarDay({
  date,
  selectedDate,
  month,
  today,
  occurrences,
}: {
  date: string;
  selectedDate: string;
  month: number;
  today: string;
  occurrences:
    FinancialCalendarEventOccurrence[];
}): FinancialCalendarDay {
  const matchingOccurrences =
    occurrences
      .filter(
        (
          occurrence,
        ) =>
          occurrence.date ===
          date,
      )
      .sort(
        compareCalendarOccurrences,
      );

  const dateObject =
    parseDateKey(
      date,
    );

  const financialTotals =
    calculateOccurrenceTotals(
      matchingOccurrences,
    );

  return {
    date,

    isCurrentMonth:
      dateObject.getMonth() +
        1 ===
      month,

    isToday:
      date ===
      today,

    isSelected:
      date ===
      selectedDate,

    isWeekend:
      dateObject.getDay() ===
        0 ||
      dateObject.getDay() ===
        6,

    occurrences:
      matchingOccurrences,

    totalScheduledAmount:
      normalizeCurrency(
        matchingOccurrences.reduce(
          (
            total,
            occurrence,
          ) =>
            total +
            Math.abs(
              occurrence.event.amount ??
                0,
            ),
          0,
        ),
      ),

    totalIncomeAmount:
      financialTotals.income,

    totalExpenseAmount:
      financialTotals.expense,

    dueCount:
      matchingOccurrences.filter(
        (
          occurrence,
        ) =>
          occurrence.status ===
          "due",
      ).length,

    pastDueCount:
      matchingOccurrences.filter(
        (
          occurrence,
        ) =>
          occurrence.status ===
          "past-due",
      ).length,

    completedCount:
      matchingOccurrences.filter(
        (
          occurrence,
        ) =>
          occurrence.status ===
          "completed",
      ).length,
  };
}

export function buildAgendaGroups(
  occurrences:
    FinancialCalendarEventOccurrence[],
): FinancialCalendarAgendaGroup[] {
  const groupedOccurrences =
    occurrences.reduce<
      Record<
        string,
        FinancialCalendarEventOccurrence[]
      >
    >(
      (
        groups,
        occurrence,
      ) => {
        const existingGroup =
          groups[
            occurrence.date
          ] ??
          [];

        return {
          ...groups,
          [occurrence.date]: [
            ...existingGroup,
            occurrence,
          ],
        };
      },
      {},
    );

  return Object.entries(
    groupedOccurrences,
  )
    .sort(
      (
        [
          firstDate,
        ],
        [
          secondDate,
        ],
      ) =>
        firstDate.localeCompare(
          secondDate,
        ),
    )
    .map(
      (
        [
          date,
          dateOccurrences,
        ],
      ) => {
        const sortedOccurrences =
          [
            ...dateOccurrences,
          ].sort(
            compareCalendarOccurrences,
          );

        const totals =
          calculateOccurrenceTotals(
            sortedOccurrences,
          );

        return {
          date,
          label:
            formatAgendaDateLabel(
              date,
            ),
          occurrences:
            sortedOccurrences,
          totalIncomeAmount:
            totals.income,
          totalExpenseAmount:
            totals.expense,
        };
      },
    );
}

export function filterCalendarEvents(
  events:
    FinancialCalendarEvent[],
  filters:
    FinancialCalendarFilters,
) {
  const normalizedSearch =
    filters.search
      .trim()
      .toLowerCase();

  return events.filter(
    (
      event,
    ) => {
      if (
        normalizedSearch
      ) {
        const searchableValue = [
          event.title,
          event.description,
          event.notes,
          event.type,
          event.status,
        ]
          .filter(
            Boolean,
          )
          .join(
            " ",
          )
          .toLowerCase();

        if (
          !searchableValue.includes(
            normalizedSearch,
          )
        ) {
          return false;
        }
      }

      if (
        filters.eventTypes.length >
          0 &&
        !filters.eventTypes.includes(
          event.type,
        )
      ) {
        return false;
      }

      if (
        filters.statuses.length >
          0 &&
        !filters.statuses.includes(
          event.status,
        )
      ) {
        return false;
      }

      if (
        filters.priorities.length >
          0 &&
        !filters.priorities.includes(
          event.priority,
        )
      ) {
        return false;
      }

      if (
        filters.accountIds.length >
          0 &&
        (
          !event.accountId ||
          !filters.accountIds.includes(
            event.accountId,
          )
        )
      ) {
        return false;
      }

      if (
        !filters.includeCompleted &&
        event.status ===
          "completed"
      ) {
        return false;
      }

      if (
        !filters.includeCanceled &&
        event.status ===
          "canceled"
      ) {
        return false;
      }

      if (
        !filters.includeAutoGenerated &&
        event.isAutoGenerated
      ) {
        return false;
      }

      if (
        !filters.includeManual &&
        !event.isAutoGenerated
      ) {
        return false;
      }

      return true;
    },
  );
}

export function applyCalendarPreferences(
  events:
    FinancialCalendarEvent[],
  preferences:
    FinancialCalendarPreferences,
) {
  return events.filter(
    (
      event,
    ) => {
      if (
        event.status ===
          "completed" &&
        !preferences.showCompletedEvents
      ) {
        return false;
      }

      if (
        event.status ===
          "canceled" &&
        !preferences.showCanceledEvents
      ) {
        return false;
      }

      switch (
        event.type
      ) {
        case "bill":
          return preferences.showBills;

        case "paycheck":
        case "income":
          return preferences.showPaychecks;

        case "transaction":
          return preferences.showTransactions;

        case "savings-contribution":
          return preferences.showSavingsContributions;

        case "debt-payment":
          return preferences.showDebtPayments;

        case "transfer":
          return preferences.showTransfers;

        case "reminder":
          return preferences.showReminders;

        case "custom":
        default:
          return preferences.showCustomEvents;
      }
    },
  );
}

export function generateCalendarOccurrences({
  events,
  range,
  today = formatDateKey(
    new Date(),
  ),
}: {
  events:
    FinancialCalendarEvent[];
  range:
    FinancialCalendarDateRange;
  today?: string;
}) {
  return events
    .flatMap(
      (
        event,
      ) =>
        generateEventOccurrences({
          event,
          range,
          today,
        }),
    )
    .sort(
      compareCalendarOccurrences,
    );
}

export function generateEventOccurrences({
  event,
  range,
  today,
}: {
  event:
    FinancialCalendarEvent;
  range:
    FinancialCalendarDateRange;
  today: string;
}): FinancialCalendarEventOccurrence[] {
  if (
    !event.recurrence
  ) {
    if (
      !isDateWithinRange(
        event.date,
        range,
      )
    ) {
      return [];
    }

    return [
      createOccurrence({
        event,
        date:
          event.date,
        today,
        isRecurringOccurrence:
          false,
      }),
    ];
  }

  const occurrenceDates =
    generateRecurringDates({
      startDate:
        event.date,
      recurrence:
        event.recurrence,
      range,
    });

  return occurrenceDates.map(
    (
      date,
    ) =>
      createOccurrence({
        event,
        date,
        today,
        isRecurringOccurrence:
          true,
      }),
  );
}

export function generateRecurringDates({
  startDate,
  recurrence,
  range,
}: {
  startDate: string;
  recurrence:
    FinancialCalendarRecurrenceRule;
  range:
    FinancialCalendarDateRange;
}) {
  const normalizedStartDate =
    normalizeCalendarDate(
      startDate,
    );

  const normalizedRange:
    FinancialCalendarDateRange = {
      startDate:
        normalizeCalendarDate(
          range.startDate,
        ),
      endDate:
        normalizeCalendarDate(
          range.endDate,
        ),
    };

  const dates:
    string[] = [];

  const maximumOccurrences =
    recurrence.endType ===
      "occurrences"
      ? Math.max(
          0,
          recurrence.occurrenceCount ??
            0,
        )
      : Number.POSITIVE_INFINITY;

  const recurrenceEndDate =
    recurrence.endType ===
      "date"
      ? recurrence.endDate
      : undefined;

  let generatedCount =
    0;

  let safetyCount =
    0;

  let currentDate =
    normalizedStartDate;

  while (
    currentDate <=
      normalizedRange.endDate &&
    generatedCount <
      maximumOccurrences &&
    safetyCount <
      5000
  ) {
    safetyCount +=
      1;

    const candidateDates =
      resolveRecurrenceCandidateDates({
        currentDate,
        startDate:
          normalizedStartDate,
        recurrence,
      });

    for (
      const candidateDate of
      candidateDates
    ) {
      if (
        candidateDate <
        normalizedStartDate
      ) {
        continue;
      }

      if (
        recurrenceEndDate &&
        candidateDate >
          recurrenceEndDate
      ) {
        return dates;
      }

      if (
        generatedCount >=
        maximumOccurrences
      ) {
        return dates;
      }

      generatedCount +=
        1;

      if (
        isDateWithinRange(
          candidateDate,
          normalizedRange,
        )
      ) {
        dates.push(
          candidateDate,
        );
      }
    }

    currentDate =
      getNextRecurrenceAnchor({
        currentDate,
        recurrence,
      });

    if (
      recurrenceEndDate &&
      currentDate >
        recurrenceEndDate
    ) {
      break;
    }
  }

  return Array.from(
    new Set(
      dates,
    ),
  ).sort();
}

export function calculateCalendarSummary({
  occurrences,
  today = formatDateKey(
    new Date(),
  ),
}: {
  occurrences:
    FinancialCalendarEventOccurrence[];
  today?: string;
}): FinancialCalendarSummary {
  const upcomingOccurrences =
    occurrences.filter(
      (
        occurrence,
      ) =>
        occurrence.date >=
          today &&
        occurrence.status !==
          "completed" &&
        occurrence.status !==
          "canceled",
    );

  const totals =
    calculateOccurrenceTotals(
      occurrences,
    );

  const nextEvent =
    upcomingOccurrences[
      0
    ];

  const nextPaycheck =
    upcomingOccurrences.find(
      (
        occurrence,
      ) =>
        occurrence.event.type ===
          "paycheck" ||
        occurrence.event.type ===
          "income",
    );

  const nextBill =
    upcomingOccurrences.find(
      (
        occurrence,
      ) =>
        occurrence.event.type ===
        "bill",
    );

  return {
    totalEventCount:
      occurrences.length,

    upcomingEventCount:
      upcomingOccurrences.length,

    dueTodayCount:
      occurrences.filter(
        (
          occurrence,
        ) =>
          occurrence.date ===
            today &&
          occurrence.status ===
            "due",
      ).length,

    pastDueCount:
      occurrences.filter(
        (
          occurrence,
        ) =>
          occurrence.status ===
          "past-due",
      ).length,

    completedCount:
      occurrences.filter(
        (
          occurrence,
        ) =>
          occurrence.status ===
          "completed",
      ).length,

    upcomingBillCount:
      upcomingOccurrences.filter(
        (
          occurrence,
        ) =>
          occurrence.event.type ===
          "bill",
      ).length,

    upcomingPaycheckCount:
      upcomingOccurrences.filter(
        (
          occurrence,
        ) =>
          occurrence.event.type ===
            "paycheck" ||
          occurrence.event.type ===
            "income",
      ).length,

    scheduledIncomeAmount:
      totals.income,

    scheduledExpenseAmount:
      totals.expense,

    netScheduledCashFlow:
      normalizeCurrency(
        totals.income -
        totals.expense,
      ),

    nextEventDate:
      nextEvent?.date,

    nextPaycheckDate:
      nextPaycheck?.date,

    nextBillDueDate:
      nextBill?.date,
  };
}

export function detectCalendarConflicts({
  occurrences,
  accountBalances = {},
  today = formatDateKey(
    new Date(),
  ),
}: {
  occurrences:
    FinancialCalendarEventOccurrence[];
  accountBalances?:
    Record<
      string,
      number
    >;
  today?: string;
}): FinancialCalendarConflict[] {
  const conflicts:
    FinancialCalendarConflict[] = [];

  const groupedByDate =
    occurrences.reduce<
      Record<
        string,
        FinancialCalendarEventOccurrence[]
      >
    >(
      (
        groups,
        occurrence,
      ) => ({
        ...groups,
        [occurrence.date]: [
          ...(
            groups[
              occurrence.date
            ] ??
            []
          ),
          occurrence,
        ],
      }),
      {},
    );

  Object.entries(
    groupedByDate,
  ).forEach(
    (
      [
        date,
        dateOccurrences,
      ],
    ) => {
      const criticalBills =
        dateOccurrences.filter(
          (
            occurrence,
          ) =>
            occurrence.event.type ===
              "bill" &&
            occurrence.event.priority ===
              "critical" &&
            occurrence.status !==
              "completed" &&
            occurrence.status !==
              "canceled",
        );

      if (
        criticalBills.length >
        1
      ) {
        conflicts.push({
          id:
            `multiple-critical-bills-${date}`,
          type:
            "multiple-critical-bills",
          severity:
            "warning",
          title:
            "Multiple critical bills are due",
          description:
            `${criticalBills.length} critical bills are scheduled on the same date.`,
          date,
          eventIds:
            criticalBills.map(
              (
                occurrence,
              ) =>
                occurrence.eventId,
            ),
          amount:
            normalizeCurrency(
              criticalBills.reduce(
                (
                  total,
                  occurrence,
                ) =>
                  total +
                  Math.abs(
                    occurrence.event.amount ??
                      0,
                  ),
                0,
              ),
            ),
          actionLabel:
            "Review bills",
          actionHref:
            "/dashboard/bills",
        });
      }

      const autopayBills =
        dateOccurrences.filter(
          (
            occurrence,
          ) =>
            occurrence.event.type ===
              "bill" &&
            occurrence.event.description
              ?.toLowerCase()
              .includes(
                "autopay",
              ),
        );

      if (
        autopayBills.length >
        1
      ) {
        conflicts.push({
          id:
            `overlapping-autopay-${date}`,
          type:
            "overlapping-autopay",
          severity:
            "info",
          title:
            "Multiple autopay charges",
          description:
            `${autopayBills.length} automatic payments are scheduled for the same date.`,
          date,
          eventIds:
            autopayBills.map(
              (
                occurrence,
              ) =>
                occurrence.eventId,
            ),
          amount:
            normalizeCurrency(
              autopayBills.reduce(
                (
                  total,
                  occurrence,
                ) =>
                  total +
                  Math.abs(
                    occurrence.event.amount ??
                      0,
                  ),
                0,
              ),
            ),
          actionLabel:
            "Review autopay bills",
          actionHref:
            "/dashboard/bills",
        });
      }
    },
  );

  occurrences.forEach(
    (
      occurrence,
    ) => {
      if (
        occurrence.status ===
        "past-due"
      ) {
        conflicts.push({
          id:
            `past-due-${occurrence.id}`,
          type:
            "past-due",
          severity:
            occurrence.event.priority ===
            "critical"
              ? "critical"
              : "warning",
          title:
            `${occurrence.event.title} is past due`,
          description:
            "This event has passed its scheduled date and still requires attention.",
          date:
            occurrence.date,
          eventIds: [
            occurrence.eventId,
          ],
          amount:
            occurrence.event.amount,
          actionLabel:
            getOccurrenceActionLabel(
              occurrence,
            ),
          actionHref:
            getOccurrenceActionHref(
              occurrence,
            ),
        });
      }

      if (
        occurrence.event.type ===
          "bill" &&
        !occurrence.event.accountId
      ) {
        conflicts.push({
          id:
            `missing-account-${occurrence.id}`,
          type:
            "missing-account",
          severity:
            "info",
          title:
            `${occurrence.event.title} has no payment account`,
          description:
            "Select an account so CASE Budget can evaluate whether enough cash is available.",
          date:
            occurrence.date,
          eventIds: [
            occurrence.eventId,
          ],
          amount:
            occurrence.event.amount,
          actionLabel:
            "Review bill",
          actionHref:
            "/dashboard/bills",
        });
      }

      if (
        occurrence.event.type ===
          "bill" &&
        occurrence.event.accountId
      ) {
        const availableAmount =
          accountBalances[
            occurrence.event.accountId
          ];

        const requiredAmount =
          Math.abs(
            occurrence.event.amount ??
              0,
          );

        if (
          typeof availableAmount ===
            "number" &&
          requiredAmount >
            availableAmount
        ) {
          conflicts.push({
            id:
              `insufficient-funds-${occurrence.id}`,
            type:
              "insufficient-funds",
            severity:
              occurrence.event.priority ===
              "critical"
                ? "critical"
                : "warning",
            title:
              `Possible shortage for ${occurrence.event.title}`,
            description:
              "The selected account balance may not cover this scheduled payment.",
            date:
              occurrence.date,
            eventIds: [
              occurrence.eventId,
            ],
            amount:
              requiredAmount,
            availableAmount:
              normalizeCurrency(
                availableAmount,
              ),
            shortageAmount:
              normalizeCurrency(
                requiredAmount -
                availableAmount,
              ),
            actionLabel:
              "Review cash flow",
            actionHref:
              "/dashboard/pay-cycles",
          });
        }
      }

      if (
        occurrence.date <
          today &&
        occurrence.status ===
          "scheduled"
      ) {
        conflicts.push({
          id:
            `unresolved-past-event-${occurrence.id}`,
          type:
            "past-due",
          severity:
            "warning",
          title:
            `${occurrence.event.title} may need an update`,
          description:
            "This scheduled event is in the past but has not been completed or skipped.",
          date:
            occurrence.date,
          eventIds: [
            occurrence.eventId,
          ],
          amount:
            occurrence.event.amount,
          actionLabel:
            getOccurrenceActionLabel(
              occurrence,
            ),
          actionHref:
            getOccurrenceActionHref(
              occurrence,
            ),
        });
      }
    },
  );

  const sortedOccurrences =
    [
      ...occurrences,
    ].sort(
      compareCalendarOccurrences,
    );

  sortedOccurrences.forEach(
    (
      occurrence,
      index,
    ) => {
      if (
        occurrence.event.type !==
        "bill"
      ) {
        return;
      }

      const previousPaycheck =
        sortedOccurrences
          .slice(
            0,
            index,
          )
          .reverse()
          .find(
            (
              candidate,
            ) =>
              candidate.event.type ===
                "paycheck" ||
              candidate.event.type ===
                "income",
          );

      const nextPaycheck =
        sortedOccurrences
          .slice(
            index +
              1,
          )
          .find(
            (
              candidate,
            ) =>
              candidate.event.type ===
                "paycheck" ||
              candidate.event.type ===
                "income",
          );

      if (
        !previousPaycheck &&
        nextPaycheck
      ) {
        conflicts.push({
          id:
            `bill-before-paycheck-${occurrence.id}`,
          type:
            "bill-before-paycheck",
          severity:
            occurrence.event.priority ===
            "critical"
              ? "critical"
              : "warning",
          title:
            `${occurrence.event.title} is due before the next paycheck`,
          description:
            `The bill is due on ${formatShortDate(
              occurrence.date,
            )}, before income scheduled for ${formatShortDate(
              nextPaycheck.date,
            )}.`,
          date:
            occurrence.date,
          eventIds: [
            occurrence.eventId,
            nextPaycheck.eventId,
          ],
          amount:
            occurrence.event.amount,
          actionLabel:
            "Open paycheck planner",
          actionHref:
            "/dashboard/pay-cycles",
        });
      }
    },
  );

  return deduplicateConflicts(
    conflicts,
  ).sort(
    compareCalendarConflicts,
  );
}

export function mergeCalendarFilters(
  currentFilters:
    FinancialCalendarFilters,
  updates:
    Partial<
      FinancialCalendarFilters
    >,
): FinancialCalendarFilters {
  return {
    ...currentFilters,
    ...updates,

    eventTypes:
      updates.eventTypes ??
      currentFilters.eventTypes,

    statuses:
      updates.statuses ??
      currentFilters.statuses,

    priorities:
      updates.priorities ??
      currentFilters.priorities,

    accountIds:
      updates.accountIds ??
      currentFilters.accountIds,
  };
}

export function mergeCalendarPreferences(
  currentPreferences:
    FinancialCalendarPreferences,
  updates:
    Partial<
      FinancialCalendarPreferences
    >,
): FinancialCalendarPreferences {
  return {
    ...currentPreferences,
    ...updates,
  };
}

export function createFinancialCalendarEventId() {
  if (
    typeof crypto !==
      "undefined" &&
    typeof crypto.randomUUID ===
      "function"
  ) {
    return `calendar-event-${crypto.randomUUID()}`;
  }

  return `calendar-event-${Date.now()}-${Math.random()
    .toString(
      36,
    )
    .slice(
      2,
      10,
    )}`;
}

export function createFinancialCalendarReminderId() {
  if (
    typeof crypto !==
      "undefined" &&
    typeof crypto.randomUUID ===
      "function"
  ) {
    return `calendar-reminder-${crypto.randomUUID()}`;
  }

  return `calendar-reminder-${Date.now()}-${Math.random()
    .toString(
      36,
    )
    .slice(
      2,
      10,
    )}`;
}

export function compareCalendarOccurrences(
  firstOccurrence:
    FinancialCalendarEventOccurrence,
  secondOccurrence:
    FinancialCalendarEventOccurrence,
) {
  const dateDifference =
    firstOccurrence.date.localeCompare(
      secondOccurrence.date,
    );

  if (
    dateDifference !==
    0
  ) {
    return dateDifference;
  }

  if (
    firstOccurrence.event.isAllDay !==
    secondOccurrence.event.isAllDay
  ) {
    return firstOccurrence.event.isAllDay
      ? -1
      : 1;
  }

  const firstTime =
    firstOccurrence.startTime ??
    "23:59";

  const secondTime =
    secondOccurrence.startTime ??
    "23:59";

  const timeDifference =
    firstTime.localeCompare(
      secondTime,
    );

  if (
    timeDifference !==
    0
  ) {
    return timeDifference;
  }

  return firstOccurrence.event.title.localeCompare(
    secondOccurrence.event.title,
  );
}

function createOccurrence({
  event,
  date,
  today,
  isRecurringOccurrence,
}: {
  event:
    FinancialCalendarEvent;
  date: string;
  today: string;
  isRecurringOccurrence: boolean;
}): FinancialCalendarEventOccurrence {
  return {
    id:
      `${event.id}-${date}`,

    eventId:
      event.id,

    date,

    startTime:
      event.startTime,

    endTime:
      event.endTime,

    status:
      resolveOccurrenceStatus({
        event,
        date,
        today,
      }),

    isRecurringOccurrence,

    originalDate:
      isRecurringOccurrence
        ? event.date
        : undefined,

    event,
  };
}

function resolveOccurrenceStatus({
  event,
  date,
  today,
}: {
  event:
    FinancialCalendarEvent;
  date: string;
  today: string;
}) {
  if (
    event.status ===
      "completed" ||
    event.status ===
      "skipped" ||
    event.status ===
      "canceled"
  ) {
    return event.status;
  }

  if (
    date <
    today
  ) {
    return "past-due";
  }

  if (
    date ===
    today
  ) {
    return "due";
  }

  return event.status;
}

function resolveRecurrenceCandidateDates({
  currentDate,
  startDate,
  recurrence,
}: {
  currentDate: string;
  startDate: string;
  recurrence:
    FinancialCalendarRecurrenceRule;
}) {
  switch (
    recurrence.frequency
  ) {
    case "weekly": {
      const weekdays =
        recurrence.weekdays?.length
          ? recurrence.weekdays
          : [
              parseDateKey(
                startDate,
              ).getDay() as FinancialCalendarWeekday,
            ];

      const weekStart =
        getStartOfWeek(
          currentDate,
          0,
        );

      return weekdays
        .map(
          (
            weekday,
          ) =>
            addCalendarDays(
              weekStart,
              weekday,
            ),
        )
        .sort();
    }

    case "biweekly": {
      const weekdays =
        recurrence.weekdays?.length
          ? recurrence.weekdays
          : [
              parseDateKey(
                startDate,
              ).getDay() as FinancialCalendarWeekday,
            ];

      const weekStart =
        getStartOfWeek(
          currentDate,
          0,
        );

      return weekdays
        .map(
          (
            weekday,
          ) =>
            addCalendarDays(
              weekStart,
              weekday,
            ),
        )
        .sort();
    }

    case "semimonthly": {
      const date =
        parseDateKey(
          currentDate,
        );

      const year =
        date.getFullYear();

      const month =
        date.getMonth() +
        1;

      const firstDay =
        Math.min(
          recurrence.firstDayOfMonth ??
            1,
          getLastDayOfMonth(
            year,
            month,
          ),
        );

      const secondDay =
        Math.min(
          recurrence.secondDayOfMonth ??
            15,
          getLastDayOfMonth(
            year,
            month,
          ),
        );

      return [
        formatDateKey(
          new Date(
            year,
            month -
              1,
            firstDay,
          ),
        ),
        formatDateKey(
          new Date(
            year,
            month -
              1,
            secondDay,
          ),
        ),
      ].sort();
    }

    case "monthly": {
      return [
        resolveMonthlyDate({
          anchorDate:
            currentDate,
          recurrence,
          fallbackDay:
            parseDateKey(
              startDate,
            ).getDate(),
        }),
      ];
    }

    case "quarterly": {
      return [
        resolveMonthlyDate({
          anchorDate:
            currentDate,
          recurrence,
          fallbackDay:
            parseDateKey(
              startDate,
            ).getDate(),
        }),
      ];
    }

    case "yearly": {
      const currentDateObject =
        parseDateKey(
          currentDate,
        );

      const startDateObject =
        parseDateKey(
          startDate,
        );

      const year =
        currentDateObject.getFullYear();

      const month =
        recurrence.monthOfYear ??
        startDateObject.getMonth() +
          1;

      const day =
        Math.min(
          recurrence.dayOfMonth ??
            startDateObject.getDate(),
          getLastDayOfMonth(
            year,
            month,
          ),
        );

      return [
        formatDateKey(
          new Date(
            year,
            month -
              1,
            day,
          ),
        ),
      ];
    }

    case "custom":
    case "daily":
    default:
      return [
        currentDate,
      ];
  }
}

function getNextRecurrenceAnchor({
  currentDate,
  recurrence,
}: {
  currentDate: string;
  recurrence:
    FinancialCalendarRecurrenceRule;
}) {
  const interval =
    Math.max(
      1,
      recurrence.interval,
    );

  switch (
    recurrence.frequency
  ) {
    case "weekly":
      return addCalendarWeeks(
        currentDate,
        interval,
      );

    case "biweekly":
      return addCalendarWeeks(
        currentDate,
        interval *
          2,
      );

    case "semimonthly":
    case "monthly":
      return addCalendarMonths(
        currentDate,
        interval,
      );

    case "quarterly":
      return addCalendarMonths(
        currentDate,
        interval *
          3,
      );

    case "yearly":
      return addCalendarYears(
        currentDate,
        interval,
      );

    case "custom":
    case "daily":
    default:
      return addCalendarDays(
        currentDate,
        interval,
      );
  }
}

function resolveMonthlyDate({
  anchorDate,
  recurrence,
  fallbackDay,
}: {
  anchorDate: string;
  recurrence:
    FinancialCalendarRecurrenceRule;
  fallbackDay: number;
}) {
  const date =
    parseDateKey(
      anchorDate,
    );

  const year =
    date.getFullYear();

  const month =
    date.getMonth() +
    1;

  const day =
    Math.min(
      recurrence.dayOfMonth ??
        fallbackDay,
      getLastDayOfMonth(
        year,
        month,
      ),
    );

  return formatDateKey(
    new Date(
      year,
      month -
        1,
      day,
    ),
  );
}

function getLastDayOfMonth(
  year: number,
  month: number,
) {
  return new Date(
    year,
    month,
    0,
  ).getDate();
}

function calculateOccurrenceTotals(
  occurrences:
    FinancialCalendarEventOccurrence[],
) {
  return occurrences.reduce(
    (
      totals,
      occurrence,
    ) => {
      if (
        occurrence.status ===
          "canceled" ||
        occurrence.status ===
          "skipped"
      ) {
        return totals;
      }

      const amount =
        Math.abs(
          occurrence.event.amount ??
            0,
        );

      if (
        isIncomeEvent(
          occurrence.event,
        )
      ) {
        return {
          income:
            normalizeCurrency(
              totals.income +
                amount,
            ),
          expense:
            totals.expense,
        };
      }

      if (
        isExpenseEvent(
          occurrence.event,
        )
      ) {
        return {
          income:
            totals.income,
          expense:
            normalizeCurrency(
              totals.expense +
                amount,
            ),
        };
      }

      return totals;
    },
    {
      income:
        0,
      expense:
        0,
    },
  );
}

function isIncomeEvent(
  event:
    FinancialCalendarEvent,
) {
  return (
    event.type ===
      "paycheck" ||
    event.type ===
      "income"
  );
}

function isExpenseEvent(
  event:
    FinancialCalendarEvent,
) {
  return (
    event.type ===
      "bill" ||
    event.type ===
      "transaction" ||
    event.type ===
      "savings-contribution" ||
    event.type ===
      "debt-payment"
  );
}

function formatAgendaDateLabel(
  value: string,
) {
  const date =
    parseDateKey(
      value,
    );

  return date.toLocaleDateString(
    "en-US",
    {
      weekday:
        "long",
      month:
        "long",
      day:
        "numeric",
      year:
        "numeric",
    },
  );
}

function formatShortDate(
  value: string,
) {
  const date =
    parseDateKey(
      value,
    );

  return date.toLocaleDateString(
    "en-US",
    {
      month:
        "short",
      day:
        "numeric",
      year:
        "numeric",
    },
  );
}

function getOccurrenceActionLabel(
  occurrence:
    FinancialCalendarEventOccurrence,
) {
  switch (
    occurrence.event.type
  ) {
    case "bill":
      return "Review bill";

    case "paycheck":
    case "income":
      return "Review pay cycle";

    case "savings-contribution":
      return "Review goal";

    case "debt-payment":
      return "Review debt";

    case "transaction":
    case "transfer":
      return "Review transaction";

    case "reminder":
    case "custom":
    default:
      return "Review event";
  }
}

function getOccurrenceActionHref(
  occurrence:
    FinancialCalendarEventOccurrence,
) {
  switch (
    occurrence.event.type
  ) {
    case "bill":
      return "/dashboard/bills";

    case "paycheck":
    case "income":
      return "/dashboard/pay-cycles";

    case "savings-contribution":
      return "/dashboard/goals";

    case "debt-payment":
      return "/dashboard/debt";

    case "transaction":
    case "transfer":
      return "/dashboard/transactions";

    case "reminder":
    case "custom":
    default:
      return "/dashboard/calendar";
  }
}

function deduplicateConflicts(
  conflicts:
    FinancialCalendarConflict[],
) {
  const uniqueConflicts =
    new Map<
      string,
      FinancialCalendarConflict
    >();

  conflicts.forEach(
    (
      conflict,
    ) => {
      if (
        !uniqueConflicts.has(
          conflict.id,
        )
      ) {
        uniqueConflicts.set(
          conflict.id,
          conflict,
        );
      }
    },
  );

  return Array.from(
    uniqueConflicts.values(),
  );
}

function compareCalendarConflicts(
  firstConflict:
    FinancialCalendarConflict,
  secondConflict:
    FinancialCalendarConflict,
) {
  const severityWeights:
    Record<
      FinancialCalendarConflict["severity"],
      number
    > = {
      critical:
        3,
      warning:
        2,
      info:
        1,
    };

  const severityDifference =
    severityWeights[
      secondConflict.severity
    ] -
    severityWeights[
      firstConflict.severity
    ];

  if (
    severityDifference !==
    0
  ) {
    return severityDifference;
  }

  const dateDifference =
    firstConflict.date.localeCompare(
      secondConflict.date,
    );

  if (
    dateDifference !==
    0
  ) {
    return dateDifference;
  }

  return firstConflict.title.localeCompare(
    secondConflict.title,
  );
}

function normalizeCurrency(
  value: number,
) {
  if (
    !Number.isFinite(
      value,
    )
  ) {
    return 0;
  }

  return (
    Math.round(
      value *
        100,
    ) /
    100
  );
}