name: Refresh KPI Summary

on:
  schedule:
    - cron: '0 0 * * *'         # every day at midnight UTC
  workflow_dispatch:           # allows manual runs from the UI

jobs:
  trigger_kpi_refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger KPI refresh
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          curl -X POST "$SUPABASE_URL/functions/v1/refresh_kpi_summary" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Content-Type: application/json"
